---
title: "NCI60 vs predictions vs PRISM comparison"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
```

```{r}
NCI_dose_response = read_csv(here('data/NCI60/DOSERESP.csv'))
NCI_klaeger_matches = read_csv(here('results/klaeger_NCI_CAS_matches.csv'))
PRISM_NCI_cell_lines = read_csv(here('results/matched_ALMANAC_cell_lines.csv'))
All_preds = read_rds(here('results/model_predictions_1500feat.rds')) %>% 
	rename(DepMap_ID = depmap_id) %>% 
	mutate(concentration_M = log10(concentration_M))
klaeger = read_rds(here('results/klaeger_full_tidy.rds'))
```

```{r}
#data processing

NCI_dose_response_filtered = NCI_dose_response %>% 
	select(NSC, CONCENTRATION, CELL_NAME, AVERAGE_PTC) %>% 
	filter(NSC %in% NCI_klaeger_matches$NSC) %>% 
	filter(CELL_NAME %in% PRISM_NCI_cell_lines$ALMANAC_NAME) %>% 
	left_join(select(PRISM_NCI_cell_lines, -PRISM_NAME), by = c('CELL_NAME' = 'ALMANAC_NAME')) %>%
	left_join(NCI_klaeger_matches, by = 'NSC') %>% 
	filter(DepMap_ID %in% All_preds$DepMap_ID & klaeger_name %in% All_preds$drug)
```

```{r}
#dose matching
klaeger_log_doses = klaeger %>% 
	select(concentration_M) %>%
	filter(concentration_M != 0) %>% 
	mutate(concentration_M = log10(concentration_M)) %>% 
	unique()

NCI_doses = NCI_dose_response_filtered %>% 
	group_by(CONCENTRATION) %>% 
	summarise(n = n())

dose_matches = NCI_doses %>% 
	inner_join(klaeger_log_doses, by = c('CONCENTRATION' = 'concentration_M')) %>% 
	mutate(klaeger_dose = CONCENTRATION) %>% 
	rename('NCI_dose' = CONCENTRATION) %>% 
	select(-n)

#find nearest doses
NCI_unmatched_doses = NCI_doses %>% 
	filter(!CONCENTRATION %in% dose_matches$NCI_dose)


nearest_klaeger_concentration = function(this_concentration, all_klaeger_concentrations) {
differences = all_klaeger_concentrations %>% 
	mutate('difference' = abs(this_concentration - concentration_M)) %>%  
	arrange(difference) 
min_difference = differences$concentration_M[1]
return(min_difference)
}

NCI_nearest_klaeger_doses = NCI_unmatched_doses %>% 
	mutate(nearest_klaeger_dose = map(CONCENTRATION, ~nearest_klaeger_concentration(., klaeger_log_doses))) %>% 
	as.data.frame() %>% 
	unnest(cols = c(nearest_klaeger_dose)) %>% 
	select(-n)
```

```{r}
#Approximated NCI60 data

trash_matches = NCI_nearest_klaeger_doses %>% 
	filter(CONCENTRATION > -4)

closest_NCI_data = NCI_dose_response_filtered %>% 
	left_join(NCI_nearest_klaeger_doses, by = c('CONCENTRATION')) %>% 
	left_join(dose_matches, by = c('CONCENTRATION' = 'NCI_dose')) %>% 
	mutate(nearest_klaeger_dose = if_else(
		is.na(nearest_klaeger_dose), 
		klaeger_dose, 
		nearest_klaeger_dose
	)) %>% 
	select(-klaeger_dose) %>% 
	left_join(All_preds, 
						by = c('DepMap_ID', 'klaeger_name' = 'drug', 'nearest_klaeger_dose' = 'concentration_M')) %>% 
	filter(!is.na(pred_via)) %>% 
	mutate(AVERAGE_PTC = AVERAGE_PTC/100) %>% 
	filter(!is.na(AVERAGE_PTC)) %>% 
	filter(!CONCENTRATION %in% trash_matches$CONCENTRATION)

closest_NCI_data %>% 
	ggplot(aes(pred_via, AVERAGE_PTC)) +
	geom_hex() +
	scale_fill_gradient(low="lightblue1",high="darkblue",trans="log10") +
	geom_smooth() +
	labs(title = paste0('Correlation = ', cor(closest_NCI_data$pred_via, closest_NCI_data$AVERAGE_PTC))) + 
	geom_abline(intercept = 0, slope = 1, size = 0.5, colour = 'red') +
	xlim(0,1.5) +
	ylim(0,1.5)

ggsave(here('figures/approximated_NCI60_vs_preds_correlation.png'), height = 7, width = 10)
```

```{r}
PRISM = read_csv(here('data/PRISM/secondary/secondary-screen-dose-response-curve-parameters.csv'))
NCI_PRISM_matches = read_csv(here('results/NCI_PRISM_matches.csv'))

PRISM_IC50s = PRISM %>% 
	select(depmap_id, ccle_name, ic50, name, passed_str_profiling) %>% 
	filter(passed_str_profiling == TRUE) %>% 
	filter(!is.na(ic50))

NCI_IC50s = read_csv(here('data/NCI60/IC50.csv'))

NCI_PRISM_IC50s = NCI_IC50s %>% 
	select(NSC, CELL_NAME, AVERAGE) %>% 
	left_join(PRISM_NCI_cell_lines, by = c('CELL_NAME' = 'ALMANAC_NAME')) %>% 
	filter(CELL_NAME %in% PRISM_NCI_cell_lines$ALMANAC_NAME) %>% 
	filter(NSC %in% NCI_PRISM_matches$NSC) %>% 
	left_join(NCI_PRISM_matches, by = 'NSC') %>% 
	select(-cid, -NCI_SID) %>% 
	left_join(PRISM_IC50s, 
						by = c('DepMap_ID' = 'depmap_id', 'PRISM_name' = 'name')) %>% 
	filter(!is.na(ic50)) %>% 
	mutate(ic50 = log10(ic50)) %>% 
	filter(ic50 > -9 & ic50 < 10)

NCI_PRISM_IC50s %>% 
	ggplot(aes(ic50, AVERAGE)) +
	geom_hex() +
	scale_fill_gradient(low="lightblue1",high="darkblue",trans="log10") +
	geom_smooth() +
	labs(title = paste0('Correlation = ', cor(NCI_PRISM_IC50s$ic50, NCI_PRISM_IC50s$AVERAGE))) + 
	geom_abline(intercept = 0, slope = 1, size = 0.5, colour = 'red')
	xlim(0,1.5) +
	ylim(0,1.5)

ggsave(here('figures/NCI60_vs_PRISM_correlation.png'), height = 7, width = 10)
```

