---
title: "Make Model Predictions"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(tictoc)
library(furrr)

knitr::opts_knit$set(root.dir = here())

dir.create(here('results/synergy_pred'), showWarnings = F)
```

```{r}
tic()
klaeger_wide = read_rds(here('results/klaeger_full_tidy.rds')) %>%
	mutate(act_gene_name = paste0("act_",gene_name)) %>%
	select(-gene_name) %>%
	pivot_wider(names_from = act_gene_name, values_from = relative_intensity)

CCLE_data = read_rds(here('results/single_model/full_CCLE_expression_set_for_ML.rds'))

rand_forest_model = read_rds(here('results/single_model_expression_regression/final_model_1500feat.rds'))

included_predictors = rand_forest_model$fit$fit$fit$forest$independent.variable.names

klaeger_wide_filtered = klaeger_wide %>%
	select(drug, concentration_M, any_of(included_predictors))

CCLE_data_filtered = CCLE_data %>%
	select(DepMap_ID, any_of(included_predictors))

sample_info = read_csv(here('data/CCLE_data/sample_info.csv.gz')) %>%
	mutate(cell_line_name_extra = paste0(cell_line_name, "\n",lineage_subtype, "\n",lineage_sub_subtype))

TNBC_lines = sample_info %>% 
	filter(cell_line_name %in% c("SK-BR-3","MCF7","MDA-MB-436","HCC1806",
															 "MDA-MB-231","BT-474","SUM-149PT","SUM-159PT",
															 "SUM-229PE"))

NCI_almanac_lines = read_csv(here('data/matched_ALMANAC_cell_lines.csv')) %>%
	filter(DepMap_ID %in% CCLE_data$DepMap_ID)

toc()
```

```{r}
calc_klaeger_combo <- function(input_drug_1, input_drug_2, input_conc_1, input_conc_2) {
	klaeger_combo = bind_rows(
		klaeger_wide_filtered %>% 
			filter(drug == input_drug_1, concentration_M == input_conc_1),
		klaeger_wide_filtered %>% 
			filter(drug == input_drug_2, concentration_M == input_conc_2)
	) %>% select(-drug,-concentration_M)
	
	return(klaeger_combo[1,]*klaeger_combo[2,])
}

tic()
if (file.exists(here('results/synergy_pred/klaeger_synergy_combos.rds'))) {
	klaeger_combo_sets = read_rds(here('results/synergy_pred/klaeger_synergy_combos.rds'))
} else {
	drug_list = sort(unique(klaeger_wide$drug))
	
	possible_klaeger_combos = crossing(
		drug_1 = drug_list,
		drug_2 = drug_list,
		concentration_M_d1 = unique(klaeger_wide$concentration_M),
		concentration_M_d2 = unique(klaeger_wide$concentration_M)
	) %>% filter(drug_1 > drug_2)
	
	klaeger_combo_sets = possible_klaeger_combos %>% 
		mutate(klaeger_combo = pmap(list(drug_1,drug_2,concentration_M_d1,concentration_M_d2),calc_klaeger_combo)) %>%
		unnest(klaeger_combo) %>%
		write_rds(here('results/synergy_pred/klaeger_synergy_combos.rds'), compress = 'gz')
}
toc()
```


```{r}
dir.create(here('results/synergy_pred/per_cell_line'), showWarnings = F)
tic()

split_lines = splitIndices(dim(klaeger_combo_sets)[1],10)

for (this_line in TNBC_lines$DepMap_ID) {
	all_pred = c()
	for (i in 1:length(split_lines)) {
		this_prediction =  predict(rand_forest_model,
															 klaeger_combo_sets %>%
															 	slice(split_lines[[i]]) %>%
															 	mutate(DepMap_ID = this_line) %>%
															 	left_join(CCLE_data_filtered) %>%
															 	mutate(klaeger_conc = NA, imputed_viability = NA,depmap_id = NA,drug=NA))
		all_pred = c(all_pred,this_prediction$.pred)
		rm(this_prediction); gc()
	}
	
	klaeger_combo_sets %>%
		mutate(DepMap_ID = this_line) %>%	
		select(DepMap_ID,drug_1,drug_2,concentration_M_d1,concentration_M_d2) %>%
		mutate(via_pred = all_pred) %>%
		write_rds(here('results/synergy_pred/per_cell_line',paste0(this_line,'.rds')), compress = 'gz')
}

toc()
```

```{r}
tic()

split_lines = splitIndices(dim(klaeger_combo_sets)[1],10)

for (this_line in NCI_almanac_lines$DepMap_ID) {
	all_pred = c()
	for (i in 1:length(split_lines)) {
		this_prediction =  predict(rand_forest_model,
															 klaeger_combo_sets %>%
															 	slice(split_lines[[i]]) %>%
															 	mutate(DepMap_ID = this_line) %>%
															 	left_join(CCLE_data_filtered, by= "DepMap_ID") %>%
															 	mutate(klaeger_conc = NA, imputed_viability = NA,depmap_id = NA,drug=NA))
		all_pred = c(all_pred,this_prediction$.pred)
		rm(this_prediction); gc()
	}
	
	klaeger_combo_sets %>%
		mutate(DepMap_ID = this_line) %>%	
		select(DepMap_ID,drug_1,drug_2,concentration_M_d1,concentration_M_d2) %>%
		mutate(via_pred = all_pred) %>%
		write_rds(here('results/synergy_pred/per_cell_line',paste0(this_line,'.rds')), compress = 'gz')
}

toc()
```