---
title: "Single Model Prediction Analysis"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(patchwork)

knitr::opts_knit$set(root.dir = here())
```

```{r}
prediction_results = read_rds(here('results/single_model_expression_regression/model_predictions_1500feat.rds')) %>%
	ungroup()

sample_info = read_csv(here('data/CCLE_data/sample_info.csv.gz')) %>%
	mutate(cell_line_name_extra = paste0(cell_line_name, "\n",lineage_subtype, "\n",lineage_sub_subtype))

avail_lines = sample_info %>% 
	filter(cell_line_name %in% c("SK-BR-3","MCF7","MDA-MB-436","HCC1806",
															 "MDA-MB-231","BT-474","SUM-149PT","SUM-159PT",
															 "SUM-229PE"))

prediction_results = prediction_results %>%
	left_join(sample_info %>% select(DepMap_ID, cell_line_name,cell_line_name_extra), by = c('depmap_id'='DepMap_ID'))
```

```{r}
avail_prediction_results = prediction_results %>%
	filter(depmap_id %in% avail_lines$DepMap_ID)
```

```{r}
get_interesting_pred_plots <- function(this_cell_line_name = "BT-474") {
	
	these_predictions = avail_prediction_results %>% 
		filter(cell_line_name == this_cell_line_name)
	
	these_summary = these_predictions %>%
		group_by(drug) %>%
		summarise(full_pred_via = mean(pred_via), 
							pred_range = max(pred_via) - min(pred_via),
							null_prox = abs(mean(pred_via - 1))) %>%
		arrange(full_pred_via)
	
	line_name_extended = unique(these_predictions$cell_line_name_extra)

	
	deadly_pred_set = these_predictions %>%
		mutate(drug = fct_relevel(drug,as.character(these_summary$drug))) %>%
		filter(drug %in% these_summary$drug[1:5])
	
	high_eff_plot = ggplot(deadly_pred_set, aes(x=log10(concentration_M), y=pred_via,color=drug)) +
		geom_point() +
		geom_line() + 
		labs(x="Log 10 Compound Concentration (M)", 
				 y="Predicted Viability",
				 color='',
				 title = paste0(this_cell_line_name, " High Effect")) +
		geom_text(data = data.frame(x=-Inf, y=-Inf,hjust=0,vjust=-0.1,label = line_name_extended),
							aes(x=x, y=y, hjust=hjust, vjust=vjust, label=label), color='black') +
		BerginskiRMisc::theme_berginski() + theme(legend.position="bottom")
	
	null_sort = these_summary %>%
		arrange(null_prox)
	
	null_eff_set = these_predictions %>%
		mutate(drug = fct_relevel(drug,as.character(null_sort$drug))) %>%
		filter(drug %in% null_sort$drug[1:5])
	
	null_eff_plot = ggplot(null_eff_set, aes(x=log10(concentration_M), y=pred_via,color=drug)) +
		geom_point() +
		geom_line() + 
		labs(x="Log 10 Compound Concentration (M)", 
				 y="Predicted Viability",
				 color='',
				 title = paste0(this_cell_line_name, " Null Effect")) +
		BerginskiRMisc::theme_berginski() + theme(legend.position="bottom")
	
	range_sort = these_summary %>%
		arrange(desc(pred_range))
	
	range_pred_set = these_predictions %>%
		mutate(drug = fct_relevel(drug,as.character(range_sort$drug))) %>%
		filter(drug %in% range_sort$drug[1:5])
	
	high_range_plot = ggplot(range_pred_set, aes(x=log10(concentration_M), y=pred_via,color=drug)) +
		geom_point() +
		geom_line() + 
		labs(x="Log 10 Compound Concentration (M)", 
				 y="Predicted Viability",
				 color='',
				 title = paste0(this_cell_line_name, " High Range")) +
		BerginskiRMisc::theme_berginski() + theme(legend.position="bottom")
	
	
	all_plots = high_eff_plot + null_eff_plot + high_range_plot
}

dir.create(here('figures/single_model_expression//avail_lines_predictions/'), showWarnings = F)
for (this_line in unique(avail_prediction_results$cell_line_name)) {
	this_plot = get_interesting_pred_plots(this_line)
	ggsave(here('figures/single_model_expression//avail_lines_predictions/',paste0(this_line,".png")), this_plot, width=15,height=5)
}
```

```{r}
line_diffs = avail_prediction_results %>%
	filter(cell_line_name == "SK-BR-3" | cell_line_name == "SUM-159PT") %>%
	select(-depmap_id,-cell_line_name_extra) %>% 
	pivot_wider(names_from = cell_line_name, values_from = pred_via) %>%
	mutate(diff = abs(`SK-BR-3` - `SUM-159PT`)) %>%
	group_by(drug) %>%
	summarise(mean_diff = mean(diff)) %>%
	arrange(desc(mean_diff))

line_diff_pred = avail_prediction_results %>%
	filter(cell_line_name == "SK-BR-3" | cell_line_name == "SUM-159PT", drug %in% line_diffs$drug[1:5]) %>%
	mutate(drug = fct_relevel(as.factor(drug),line_diffs$drug))

ggplot(line_diff_pred, aes(x=log10(concentration_M), y=pred_via,color=paste0("\n",cell_line_name_extra,"\n"))) +
	geom_point() +
	geom_line() + 
	labs(x="Log 10 Compound Concentration (M)", 
			 y="Predicted Viability",
			 color='') +
	BerginskiRMisc::theme_berginski() +
	facet_wrap(~drug)
ggsave(here('figures/single_model_expression//avail_lines_predictions/SK-BR_vs_SUM159.png'))
```

```{r}
line_diffs = avail_prediction_results %>%
	filter(cell_line_name == "BT-474" | cell_line_name == "HCC1806") %>%
	select(-depmap_id,-cell_line_name_extra) %>% 
	pivot_wider(names_from = cell_line_name, values_from = pred_via) %>%
	mutate(diff = abs(`BT-474` - `HCC1806`)) %>%
	group_by(drug) %>%
	summarise(mean_diff = mean(diff)) %>%
	arrange(desc(mean_diff))

line_diff_pred = avail_prediction_results %>%
	filter(cell_line_name == "BT-474" | cell_line_name == "HCC1806", drug %in% line_diffs$drug[1:5]) %>%
	mutate(drug = fct_relevel(as.factor(drug),line_diffs$drug))

ggplot(line_diff_pred, aes(x=log10(concentration_M), y=pred_via,color=paste0("\n",cell_line_name_extra,"\n"))) +
	geom_point() +
	geom_line() + 
	labs(x="Log 10 Compound Concentration (M)", 
			 y="Predicted Viability",
			 color='') +
	BerginskiRMisc::theme_berginski() +
	facet_wrap(~drug)
ggsave(here('figures/single_model_expression//avail_lines_predictions/BT-474_vs_HCC1806.png'))
```

# Cell Line Summaries

```{r}
all_line_summary = prediction_results %>% 
	group_by(cell_line_name,DepMap_ID,drug) %>%
	summarise(full_pred_via = mean(pred_via), pred_range = max(pred_via) - min(pred_via))


```