---
title: "Annotate Kinase Interactors"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(DarkKinaseTools)
library(tictoc)

knitr::opts_knit$set(root.dir = here())
```

```{r}
full_model_data_set_500feat <- readRDS(here("results/single_model_expression_regression/full_model_data_set_500feat.rds"))

string_data = read_delim(here('data/STRING/9606.protein.links.v11.5.txt.gz')) %>%
	filter(combined_score >= 700) %>%
	separate(protein1, into=c(NA,"ENSP_prot1"), sep = "\\.") %>%
	separate(protein2, into=c(NA,"ENSP_prot2"), sep = "\\.")

CCLE_data = read_rds(here('results/single_model/full_CCLE_expression_set_for_ML.rds'))

all_exp_genes = data.frame(act_hgnc = names(CCLE_data)) %>%
	filter(act_hgnc != "DepMap_ID") %>%
	separate(act_hgnc,into = c(NA,"hgnc"), sep = "_", remove = F)
```

```{r}
ensembl <- biomaRt::useEnsembl(biomart = "genes", dataset = "hsapiens_gene_ensembl")
hgnc_to_ENSP = biomaRt::getBM(attributes = c('hgnc_symbol','ensembl_peptide_id'), mart = ensembl)
```

```{r}
model_features = data.frame(temp = names(full_model_data_set_500feat)) %>%
	separate(temp, into = c("type",'hgnc'), sep = "_") %>%
	separate_rows(hgnc,sep = ";") %>%
	filter(!is.na(hgnc), hgnc != "viability", hgnc != "id", hgnc != "conc") %>%
	identity()

model_features_interact = model_features %>% 
	left_join(hgnc_to_ENSP, by=c('hgnc'='hgnc_symbol')) %>%
	#the STRING data file has both protein interactions directions listed, so we
	#only need to join against protein 1 to the full interaction list.
	# http://version10.string-db.org/help/faq/
	left_join(string_data, by=c('ensembl_peptide_id' = 'ENSP_prot1')) %>%
	filter(ensembl_peptide_id != '', !is.na(ENSP_prot2)) %>%
	identity()

model_features_act = model_features_interact %>%
	filter(type == "act")

model_features_exp_direct_act = model_features_interact %>%
	filter(type == "exp") %>%
	left_join(model_features_act %>%
							select(hgnc,ensembl_peptide_id) %>%
							unique() %>%
							rename(act_hgnc = hgnc),
						by = c('ENSP_prot2' = "ensembl_peptide_id")) %>%
	filter(!is.na(act_hgnc))

model_features_direct_count = model_features_exp_direct_act %>%
	group_by(hgnc) %>%
	count(name = "direct_count")

all_kinase_id = all_kinases %>%
	select(symbol, class) %>%
	left_join(hgnc_to_ENSP, by=c('symbol' = 'hgnc_symbol'))

model_features_exp_kinase_interact = model_features_interact %>%
	filter(type == "exp") %>%
	left_join(all_kinase_id, by = c('ENSP_prot2' = "ensembl_peptide_id")) %>%
	filter(!is.na(class))

model_features_exp_kinase_count = model_features_exp_kinase_interact %>%
	group_by(hgnc) %>%
	count(name = "kinase_count")

model_features = model_features %>%
	filter(type == "exp") %>%
	left_join(model_features_direct_count) %>%
	left_join(model_features_exp_kinase_count) %>% 
	mutate(direct_count = ifelse(is.na(direct_count), 0, direct_count))

write_rds(model_features,here('results/single_model_expression_regression/expression_feature_interactors.rds'))
```

```{r}
activation_genes = data.frame(temp = names(full_model_data_set_500feat)) %>%
	separate(temp, into = c("type",'hgnc'), sep = "_") %>%
	separate_rows(hgnc,sep = ";") %>%
	filter(!is.na(hgnc), hgnc != "viability", hgnc != "id", hgnc != "conc") %>%
	filter(type == "act") %>%
	left_join(hgnc_to_ENSP, by=c('hgnc'='hgnc_symbol'))

count_direct_interactors_random <- function() {
	activation_interactor_set = all_exp_genes %>%
		slice_sample(n = 110) %>%
		left_join(hgnc_to_ENSP, by=c('hgnc'='hgnc_symbol')) %>%
		#the STRING data file has both protein interactions directions listed, so we
		#only need to join against protein 1 to the full interaction list.
		# http://version10.string-db.org/help/faq/
		left_join(string_data, by=c('ensembl_peptide_id' = 'ENSP_prot1')) %>%
		filter(ensembl_peptide_id != '', !is.na(ENSP_prot2)) %>%
		filter(ENSP_prot2 %in% activation_genes$ensembl_peptide_id) %>% 
		group_by(hgnc) %>% 
		count()

	return(data.frame(count = length(unique(activation_interactor_set$hgnc)),
										mean_interactors = mean(c(activation_interactor_set$n, rep(0,110 - length(activation_interactor_set$n))))))
}

tic()
interactor_count = data.frame()
for (i in 1:10000) {
	interactor_count = rbind(interactor_count,
													 count_direct_interactors_random())
}
toc()
```

