---
title: "Assess Classification Models"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(ROCR)
library(patchwork)
library(tictoc)
library(broom)
library(gghighlight)
library(Metrics)

knitr::opts_knit$set(root.dir = here())
model_results = data.frame()
all_pred = data.frame()
```

# Inhibition/Expression Comparisons

```{r}
tic()

for (feat_count in c(100,200,300,400,500,600,700,800,900,1000,1500,2000)) {
	model_files = Sys.glob(here('results/single_model_expression_regression/rand_forest/',
															sprintf('%dfeat_notune_pred',feat_count),
															"*"))
	
	for (this_file in model_files) {
		these_cv_results = read_rds(this_file) %>%
			mutate(fold_file = basename(this_file),
						 feat_count = feat_count)
		
		model_results = bind_rows(
			model_results,
			data.frame(feat_count = feat_count,
								 trees = 500,
								 fold_file = basename(this_file),
								 model_type = 'rand_forest',
								 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
								 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
	}
	
}
toc()
```

```{r}
tic()

for (feat_count in c(100,200,300,400,500)) {
	model_files = Sys.glob(here('results/single_model_act_only_regression/rand_forest/',
															sprintf('%dfeat_notune_pred',feat_count),
															"*"))
	
	for (this_file in model_files) {
		these_cv_results = read_rds(this_file) %>%
			mutate(fold_file = basename(this_file),
						 feat_count = feat_count)
		
		model_results = bind_rows(
			model_results,
			data.frame(feat_count = feat_count,
								 trees = 500,
								 fold_file = basename(this_file),
								 model_type = 'rand_forest_act_only',
								 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
								 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
	}
	
}
toc()
```

```{r}
tic()

for (feat_count in c(100,200,300,400,500,1000,1500,2000)) {
	model_files = Sys.glob(here('results/single_model_exp_only_regression/rand_forest/',
															sprintf('%dfeat_notune_pred',feat_count),
															"*"))
	
	for (this_file in model_files) {
		these_cv_results = read_rds(this_file) %>%
			mutate(fold_file = basename(this_file),
						 feat_count = feat_count)
		
		model_results = bind_rows(
			model_results,
			data.frame(feat_count = feat_count,
								 trees = 500,
								 fold_file = basename(this_file),
								 model_type = 'rand_forest_exp_only',
								 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
								 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
	}
	
}
toc()
```

## Naive Average Model

```{r}
fold_ids = read_rds(here('results/single_model_expression_regression/CV_split_row_nums.rds'))

PRISM_klaeger_imputed = read_rds(here('results/PRISM_klaeger_imputed_tidy.rds'))

CCLE_data = read_rds(here('results/single_model/full_CCLE_expression_set_for_ML.rds'))

PRISM_klaeger_imputed = PRISM_klaeger_imputed %>%
	filter(depmap_id %in% CCLE_data$DepMap_ID) %>%
	ungroup()

CV_aver_eff = data.frame()

for (this_fold_id in unique(fold_ids)) {
	aver_eff = PRISM_klaeger_imputed %>% 
		slice(which(fold_ids != this_fold_id)) %>%
		group_by(klaeger_conc) %>%
		# group_by(drug) %>%
		summarise(aver_via = mean(imputed_viability)) %>%
		ungroup()
	
	CV_aver_eff = bind_rows(
		CV_aver_eff,
		PRISM_klaeger_imputed %>%
			slice(which(fold_ids == this_fold_id)) %>%
			left_join(aver_eff)
	)
}

naive_average_r2 = cor(CV_aver_eff$imputed_viability,CV_aver_eff$aver_via)^2
naive_average_rmse = Metrics::rmse(CV_aver_eff$imputed_viability,CV_aver_eff$aver_via)
```



```{r}
model_summary = model_results %>% 
	filter(model_type %in% c("rand_forest","rand_forest_act_only","rand_forest_exp_only")) %>%
	group_by(feat_count,trees,model_type) %>% 
	nest() %>%
	mutate(rmse = map(data, ~ tidy(t.test(.x$rmse)))) %>%
	mutate(r2 = map(data, ~ tidy(t.test(.x$r2)))) %>%
	unnest(cols=c(rmse,r2),names_sep = "_") %>%
	mutate(model_type_FN = as.factor(case_when(
		model_type == "rand_forest" ~ "Inhibition and Expression",
		model_type == "rand_forest_act_only" ~ "Inhibition Only",
		model_type == "rand_forest_exp_only" ~ "Expression Only",
	))) %>%
	mutate(model_type_FN = fct_relevel(model_type_FN, 
																		 c("Inhibition and Expression","Inhibition Only","Expression Only"))) %>%
	select(model_type,feat_count,trees,r2_estimate,rmse_estimate,everything()) %>%
	filter(feat_count <= 500)
```

## Figures

```{r}
dir.create(here('figures/single_model_expression'), recursive = T)

r2_plot = ggplot(model_summary, 
								 aes(y=r2_estimate,x=feat_count, color=model_type_FN, shape=model_type_FN)) + 
	geom_hline(aes(yintercept = naive_average_r2), linetype = 2, alpha = 0.5) +
	geom_point(size=1.5) + 
	# geom_errorbar(aes(ymin=r2_conf.low,ymax=r2_conf.high)) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	# scale_x_continuous(breaks=c(200,500,1000,1500)) +
	labs(x="Number of Features",y="R\u00B2", color="",shape="") +
	BerginskiRMisc::theme_berginski()

rmse_plot = ggplot(model_summary, 
									 aes(y=rmse_estimate,x=feat_count, color=model_type_FN, shape=model_type_FN)) + 
	geom_hline(aes(yintercept = naive_average_rmse), linetype = 2, alpha = 0.5) +
	geom_point(size=1.5) + 
	# geom_errorbar(aes(ymin=rmse_conf.low,ymax=rmse_conf.high)) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	# scale_x_continuous(breaks=c(200,500,1000,1500)) +
	labs(x="Number of Features",y="RMSE",color="",shape="") +
	BerginskiRMisc::theme_berginski()

ggsave(here('figures/single_model_expression/model_comparison_act_expr_only.png'),
			 r2_plot + rmse_plot +
			 	plot_layout(guides = "collect") & 
			 	theme(legend.position = 'bottom', legend.margin=margin(0,0,0,0), legend.box.margin=margin(-10,-10,-10,-10)),
			 width=6*0.8,height=3*0.8)
BerginskiRMisc::trimImage(here('figures/single_model_expression/model_comparison_act_expr_only.png'))
```

# Only Kinases Model Comparison

```{r}
tic()

for (feat_count in c(100,200,300,400,500,1000,1500,2000)) {
	model_files = Sys.glob(here('results/single_model_exp_only_kin_regression/rand_forest/',
															sprintf('%dfeat_notune_pred',feat_count),
															"*"))
	
	for (this_file in model_files) {
		these_cv_results = read_rds(this_file) %>%
			mutate(fold_file = basename(this_file),
						 feat_count = feat_count)
		
		model_results = bind_rows(
			model_results,
			data.frame(feat_count = feat_count,
								 trees = 500,
								 fold_file = basename(this_file),
								 model_type = 'rand_forest_only_kin',
								 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
								 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
	}
	
}
toc()
```

```{r}
model_summary = model_results %>% 
	filter(model_type %in% c("rand_forest","rand_forest_only_kin")) %>%
	group_by(feat_count,trees,model_type) %>% 
	nest() %>%
	mutate(rmse = map(data, ~ tidy(t.test(.x$rmse)))) %>%
	mutate(r2 = map(data, ~ tidy(t.test(.x$r2)))) %>%
	unnest(cols=c(rmse,r2),names_sep = "_") %>%
	mutate(model_type_FN = as.factor(case_when(
		model_type == "rand_forest" ~ "All Inhibition Data",
		model_type == "rand_forest_only_kin" ~ "Only Kinase Inhibition Data"
	))) %>%
	mutate(model_type_FN = fct_relevel(model_type_FN, 
																		 c("All Inhibition Data","Only Kinase Inhibition Data"))) %>%
	select(model_type,feat_count,trees,r2_estimate,rmse_estimate,everything())
```

## Figures

```{r}
dir.create(here('figures/single_model_expression'), recursive = T)

r2_plot = ggplot(model_summary, 
								 aes(y=r2_estimate,x=feat_count, color=model_type_FN, shape=model_type_FN)) + 
	geom_hline(aes(yintercept = naive_average_r2), linetype = 2, alpha = 0.5) +
	geom_point(size=1.5) + 
	# geom_errorbar(aes(ymin=r2_conf.low,ymax=r2_conf.high)) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	# scale_x_continuous(breaks=c(200,500,1000,1500)) +
	labs(x="Number of Features",y="R\u00B2", color="",shape="") +
	BerginskiRMisc::theme_berginski()

rmse_plot = ggplot(model_summary, 
									 aes(y=rmse_estimate,x=feat_count, color=model_type_FN, shape=model_type_FN)) + 
	geom_hline(aes(yintercept = naive_average_rmse), linetype = 2, alpha = 0.5) +
	geom_point(size=1.5) + 
	# geom_errorbar(aes(ymin=rmse_conf.low,ymax=rmse_conf.high)) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	# scale_x_continuous(breaks=c(200,500,1000,1500)) +
	labs(x="Number of Features",y="RMSE",color="",shape="") +
	BerginskiRMisc::theme_berginski()

ggsave(here('figures/single_model_expression/model_comparison_only_kin.png'),
			 r2_plot + rmse_plot +
			 	plot_layout(guides = "collect") & 
			 	theme(legend.position = 'bottom', legend.margin=margin(0,0,0,0), legend.box.margin=margin(-10,-10,-10,-10)),
			 width=6*0.8,height=3*0.8)
BerginskiRMisc::trimImage(here('figures/single_model_expression/model_comparison_only_kin.png'))
```