---
title: "Assess Classification Models"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(ROCR)
library(patchwork)
library(tictoc)
library(broom)
library(gghighlight)
library(Metrics)

knitr::opts_knit$set(root.dir = here())
model_results = data.frame()
all_pred = data.frame()
```

# Rand Forest Model Assessment

```{r}
tic()

for (feat_count in c(100,200,300,400,500,600,700,800,900,1000,1500,2000)) {
	model_files = Sys.glob(here('results/single_model_expression_regression/rand_forest/',
															sprintf('%dfeat_notune_pred',feat_count),
															"*"))
	
	for (this_file in model_files) {
		these_cv_results = read_rds(this_file) %>%
			mutate(fold_file = basename(this_file),
						 feat_count = feat_count)
		
		model_results = bind_rows(
			model_results,
			data.frame(feat_count = feat_count,
								 trees = 500,
								 fold_file = basename(this_file),
								 model_type = 'rand_forest',
								 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
								 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
	}
}
toc()
```

# XGBoost Model Assessment

```{r}
tic()

for (feat_count in c(100,200,300,400,500,1000,1500,2000)) {
	model_files = Sys.glob(here('results/single_model_expression_regression/xgboost/',
															sprintf('%dfeat_notune_pred',feat_count),
															"*"))
	
	for (this_file in model_files) {
		these_cv_results = read_rds(this_file) %>%
			mutate(fold_file = basename(this_file),
						 feat_count = feat_count)
		
		model_results = bind_rows(
			model_results,
			data.frame(feat_count = feat_count,
								 trees = NA,
								 fold_file = basename(this_file),
								 model_type = 'xgboost',
								 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
								 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
	}
	
}
toc()
```

# Linear Model Assessment

```{r}
tic()

for (feat_count in c(100,200,300,400,500,1000,1500,2000)) {
	model_files = Sys.glob(here('results/single_model_expression_regression/linear/',
															sprintf('%dfeat_notune_pred',feat_count),
															"*"))
	
	for (this_file in model_files) {
		these_cv_results = read_rds(this_file) %>%
			mutate(fold_file = basename(this_file),
						 feat_count = feat_count)
		
		model_results = bind_rows(
			model_results,
			data.frame(feat_count = feat_count,
								 trees = NA,
								 fold_file = basename(this_file),
								 model_type = 'linear',
								 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
								 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
	}
	
}
toc()
```

# Tabnet Model Assessment

```{r}
tic()

for (feat_count in c(100,200,300,400,500,1000,1500,2000)) {
	model_files = Sys.glob(here('results/single_model_expression_regression/tabnet/',
															sprintf('%dfeat_notune_pred',feat_count),
															"*"))
	
	for (this_file in model_files) {
		these_cv_results = read_rds(this_file) %>%
			mutate(fold_file = basename(this_file),
						 feat_count = feat_count)
		
		model_results = bind_rows(
			model_results,
			data.frame(feat_count = feat_count,
								 trees = NA,
								 fold_file = basename(this_file),
								 model_type = 'tabnet',
								 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
								 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
	}
	
}
toc()
```

# Naive Average Model

```{r}
fold_ids = read_rds(here('results/single_model_expression_regression/CV_split_row_nums.rds'))

PRISM_klaeger_imputed = read_rds(here('results/PRISM_klaeger_imputed_tidy.rds'))

CCLE_data = read_rds(here('results/single_model/full_CCLE_expression_set_for_ML.rds'))

PRISM_klaeger_imputed = PRISM_klaeger_imputed %>%
	filter(depmap_id %in% CCLE_data$DepMap_ID) %>%
	ungroup()

CV_aver_eff = data.frame()

for (this_fold_id in unique(fold_ids)) {
	aver_eff = PRISM_klaeger_imputed %>% 
		slice(which(fold_ids != this_fold_id)) %>%
		group_by(klaeger_conc) %>%
		# group_by(drug) %>%
		summarise(aver_via = mean(imputed_viability)) %>%
		ungroup()
	
	CV_aver_eff = bind_rows(
		CV_aver_eff,
		PRISM_klaeger_imputed %>%
			slice(which(fold_ids == this_fold_id)) %>%
			left_join(aver_eff)
	)
}

naive_average_r2 = cor(CV_aver_eff$imputed_viability,CV_aver_eff$aver_via)^2
naive_average_rmse = Metrics::rmse(CV_aver_eff$imputed_viability,CV_aver_eff$aver_via)
```

```{r}
model_summary = model_results %>% 
	group_by(feat_count,trees,model_type) %>% 
	nest() %>%
	mutate(rmse = map(data, ~ tidy(t.test(.x$rmse)))) %>%
	mutate(r2 = map(data, ~ tidy(t.test(.x$r2)))) %>%
	unnest(cols=c(rmse,r2),names_sep = "_") %>%
	mutate(model_type_FN = case_when(
		model_type == "rand_forest" ~ "Random Forest",
		model_type == "xgboost" ~ "XGBoost",
		model_type == "linear" ~ "Linear Regresssion",
		model_type == "tabnet" ~ "TabNet"
	)) %>%
	select(model_type,feat_count,trees,r2_estimate,rmse_estimate,everything()) %>%
	mutate(model_type_FN = as.factor(model_type_FN)) %>%
	mutate(model_type_FN = fct_relevel(model_type_FN, "TabNet", after=Inf))


# single_pred_set = all_pred %>% 
# 	filter(model_type == "rand_forest", trees == 500, feat_count == 1500) %>% 
# 	mutate(worst_pred = case_when(
# 		target_viability <= 1 ~ 0,
# 		T ~ 2
# 	))
# 
# worst_rmse = sqrt(mean((single_pred_set$worst_pred - single_pred_set$target_viability)^2))
```

# Figures

```{r}
dir.create(here('figures/single_model_expression'), recursive = T)

r2_plot = ggplot(model_summary, 
								 aes(y=r2_estimate,x=feat_count, color=model_type_FN, shape=model_type_FN)) + 
	geom_hline(aes(yintercept = naive_average_r2), linetype = 2, alpha = 0.5) +
	geom_point(size=1.5) + 
	# geom_errorbar(aes(ymin=r2_conf.low,ymax=r2_conf.high)) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	# scale_x_continuous(breaks=c(200,500,1000,1500)) +
	labs(x="Number of Features",y="R\u00B2", color="",shape="") +
	BerginskiRMisc::theme_berginski()

rmse_plot = ggplot(model_summary, 
									 aes(y=rmse_estimate,x=feat_count, color=model_type_FN, shape=model_type_FN)) + 
	geom_hline(aes(yintercept = naive_average_rmse), linetype = 2, alpha = 0.5) +
	geom_point(size=1.5) + 
	# geom_errorbar(aes(ymin=rmse_conf.low,ymax=rmse_conf.high)) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	# scale_x_continuous(breaks=c(200,500,1000,1500)) +
	labs(x="Number of Features",y="RMSE",color="",shape="") +
	BerginskiRMisc::theme_berginski()

ggsave(here('figures/single_model_expression/model_comparison.png'),
			 r2_plot + rmse_plot +
			 	plot_layout(guides = "collect") & 
			 	theme(legend.position = 'bottom', legend.margin=margin(0,0,0,0), legend.box.margin=margin(-10,-10,-10,-10)),
			 width=6*0.8,height=3*0.8)
BerginskiRMisc::trimImage(here('figures/single_model_expression/model_comparison.png'))
```

```{r}
# dir.create(here('figures/single_model_expression'), recursive = T)
# 
# r2_plot = ggplot(model_summary %>% 
# 								 	filter(trees == 500, model_type == "rand_forest"), 
# 								 aes(y=r2_estimate,x=feat_count)) + 
# 	geom_hline(aes(yintercept = naive_average_r2), linetype = 2, alpha = 0.5) +
# 	geom_point() + 
# 	# geom_errorbar(aes(ymin=r2_conf.low,ymax=r2_conf.high)) +
# 	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
# 	labs(x="Number of Features",y="R\u00B2") +
# 	gghighlight(feat_count == 1500) +
# 	BerginskiRMisc::theme_berginski()
# 
# rmse_plot = ggplot(model_summary %>% 
# 									 	filter(trees == 500, model_type == "rand_forest"), 
# 									 aes(y=rmse_estimate,x=feat_count)) + 
# 	geom_hline(aes(yintercept = naive_average_rmse), linetype = 2, alpha = 0.5) +
# 	geom_point() + 
# 	# geom_errorbar(aes(ymin=rmse_conf.low,ymax=rmse_conf.high)) +
# 	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
# 	labs(x="Number of Features",y="RMSE") +
# 	gghighlight(feat_count == 1500) +
# 	BerginskiRMisc::theme_berginski()
# 
# ggsave(here('figures/single_model_expression/rand_forest_feature_counts.png'),
# 			 r2_plot + rmse_plot,
# 			 width=6*0.8,height=3*0.8)
# BerginskiRMisc::trimImage(here('figures/single_model_expression/rand_forest_feature_counts.png'))
```

```{r}
best_pred = Sys.glob(here('results/single_model_expression_regression/rand_forest/500feat_notune_pred/*')) %>%
	map(~read_rds(.x)) %>%
	reduce(rbind) %>%
	mutate(viability_binned = cut(target_viability,
																seq(0,1,by=0.05),
																include.lowest = T))

binned_summary = best_pred %>%
	group_by(viability_binned) %>%
	summarise(median_via = median(target_viability))

best_model_summary = model_summary %>% 
	filter(model_type == "rand_forest", feat_count == 500, trees == 500)

summary_text = paste0("R\u00B2: ",signif(best_model_summary$r2_estimate,3), "\n",
											"RMSE: ",signif(best_model_summary$rmse_estimate,3))

summary_title = paste0("R\u00B2: ",signif(best_model_summary$r2_estimate,3), " / ",
											 "RMSE: ",signif(best_model_summary$rmse_estimate,3))

ggplot(best_pred, aes(x=target_viability,y=.pred)) +
	stat_binhex(aes(fill=log10(..count..))) +
	geom_abline(slope = 1, intercept = 0, color='black', alpha=0.5, linetype = 2) +
	geom_smooth(color = 'red') +
	scale_fill_viridis_c() +
	labs(x="Actual Imputed Viability", y="Predicted Viability",fill="Log10\n# Values") +
	# geom_text(aes(x=-Inf,y=Inf,hjust=-0.1,vjust=1,label=summary_text), size=3.5, color='blue') +
	BerginskiRMisc::theme_berginski() +
	ggtitle(summary_title) +
	# xlim(c(0,2)) + ylim(c(0,2)) +
	theme(aspect.ratio = 1:1, legend.margin=margin(0,0,0,0), legend.box.margin=margin(-10,-5,-10,-10))

ggsave(here('figures/single_model_expression/viability_vs_pred_best_hex.png'),height=3,width=3)
BerginskiRMisc::trimImage(here('figures/single_model_expression/viability_vs_pred_best_hex.png'))

ggplot(best_pred, aes(x=viability_binned,y=.pred)) +
	geom_boxplot() +
	geom_point(data = binned_summary, aes(x=viability_binned,y=median_via), color = 'blue') +
	labs(x="Binned Viability Ranges", y="Predicted Viability") +
	BerginskiRMisc::theme_berginski() +
	geom_text(aes(x=-Inf,y=Inf,hjust=0,vjust=1,label=summary_text), color='black') +
	# xlim(c(0,2)) + ylim(c(0,2)) +
	theme(aspect.ratio = 1:1) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggsave(here('figures/single_model_expression/viability_vs_pred_best_box.png'),heigh=5,width=5)
BerginskiRMisc::trimImage(here('figures/single_model_expression/viability_vs_pred_best_box.png'))
```

```{r}
ggplot(CV_aver_eff, aes(x=imputed_viability,y=aver_via)) +
	stat_binhex(aes(fill=log10(..count..))) +
	geom_abline(slope = 1, intercept = 0, color='black', alpha=0.5, linetype = 2) +
	geom_smooth(color = 'blue') +
	scale_fill_viridis_c() +
	labs(x="Actual Imputed Viability", y="Dose-Only Predicted Viability",fill="Log10\n# Values") +
	# geom_text(aes(x=-Inf,y=Inf,hjust=-0.1,vjust=1,label=summary_text), size=3.5, color='blue') +
	BerginskiRMisc::theme_berginski() +
	# ggtitle(summary_title) +
	xlim(c(0,1)) + ylim(c(0,1)) +
	theme(aspect.ratio = 1:1, legend.margin=margin(0,0,0,0), legend.box.margin=margin(-10,-5,-10,-10))

ggsave(here('figures/single_model_expression/viability_vs_dose_only_hex.png'),height=3,width=3)
BerginskiRMisc::trimImage(here('figures/single_model_expression/viability_vs_dose_only_hex.png'))
```

# Rand Forest Tree Count Tuning

```{r}
model_tuning_results = data.frame()

for (feat_count in c(500,1000,1500,2000)) {
	for (tree_count in c(1000,1500,2000)) {
		model_files = Sys.glob(here('results/single_model_expression_regression/rand_forest_tune/',
																sprintf('%dfeat_%dtrees_pred',feat_count,tree_count),
																"*"))
		
		for (this_file in model_files) {
			these_cv_results = read_rds(this_file) %>%
				mutate(fold_file = basename(this_file),
							 feat_count = feat_count)
			
			model_tuning_results = bind_rows(
				model_tuning_results,
				data.frame(feat_count = feat_count,
									 fold_file = basename(this_file),
									 tree_count = tree_count,
									 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
									 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
		}
	}
}

for (feat_count in c(500,1000,1500,2000)) {
	model_files = Sys.glob(here('results/single_model_expression_regression/rand_forest/',
															sprintf('%dfeat_notune_pred',feat_count),
															"*"))
	
	for (this_file in model_files) {
		these_cv_results = read_rds(this_file) %>%
			mutate(fold_file = basename(this_file),
						 feat_count = feat_count)
		
		model_tuning_results = bind_rows(
			model_tuning_results,
			data.frame(feat_count = feat_count,
								 tree_count = 500,
								 fold_file = basename(this_file),
								 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
								 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
	}
}

model_tuning_results_summary = model_tuning_results %>% 
	group_by(feat_count,tree_count) %>% 
	nest() %>%
	mutate(rmse = map(data, ~ tidy(t.test(.x$rmse)))) %>%
	mutate(r2 = map(data, ~ tidy(t.test(.x$r2)))) %>%
	unnest(cols=c(rmse,r2),names_sep = "_") %>%
	select(feat_count,tree_count,r2_estimate,rmse_estimate,everything())
```

```{r}
r2_plot = ggplot(model_tuning_results_summary,
								 aes(y=r2_estimate,x=as.factor(feat_count), color=as.factor(tree_count))) +
	geom_point(position=position_dodge(width=0.85)) +
	# geom_errorbar(aes(ymin=r2_conf.low,ymax=r2_conf.high),
	# 							position=position_dodge(width=0.5)) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	labs(x="Number of Features",y="R\u00B2",color="# Trees") +
	BerginskiRMisc::theme_berginski()

rmse_plot = ggplot(model_tuning_results_summary,
									 aes(y=rmse_estimate,x=as.factor(feat_count), color=as.factor(tree_count))) +
	geom_point(position=position_dodge(width=0.85)) +
	# geom_errorbar(aes(ymin=rmse_conf.low,ymax=rmse_conf.high),
	# 							position=position_dodge(width=0.5)) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	labs(x="Number of Features",y="RMSE",color="# Trees") +
	BerginskiRMisc::theme_berginski()

ggsave(here('figures/single_model_expression/rand_forest_tree_count.png'),
			 r2_plot + rmse_plot + plot_layout(guides = "collect") & 
			 	theme(legend.position = 'bottom', legend.margin=margin(0,0,0,0), legend.box.margin=margin(-10,-10,-10,-10)),width=4.5,height=2.25)
BerginskiRMisc::trimImage(here('figures/single_model_expression/rand_forest_tree_count.png'))
```

# Additional Model Tuning Attempts

```{r}
model_tuning_results = data.frame()

model_files = Sys.glob(here('results/single_model_expression_regression/rand_forest_more_tune/500feat_500trees_pred/*'))

for (this_file in model_files) {
	these_cv_results = read_rds(this_file) %>%
		mutate(fold_file = basename(this_file)) %>%
		group_by(mtry,min_n) %>% 
		summarise(rmse = rmse(target_viability,.pred),
							r2 = glance(summary(lm(.pred ~ target_viability)))$r.squared)
	
	model_tuning_results = bind_rows(
		model_tuning_results,
		these_cv_results
	)
}

model_tuning_summary = model_tuning_results %>% 
	group_by(mtry,min_n) %>% 
	summarize(mean_rmse = mean(rmse), 
						mean_r2 = mean(r2))
```
```{r}
more_rmse = ggplot(model_tuning_summary, aes(x=mtry, y=min_n, color=mean_r2)) +
	geom_point() +
	labs(x="# Selected Predictors",
			 y="Minimal Node Size",
			 color="R\u00B2") +
	BerginskiRMisc::theme_berginski()

more_r2 = ggplot(model_tuning_summary, aes(x=mtry, y=min_n, color=mean_rmse)) +
	geom_point() +
	labs(x="# Selected Predictors",
			 y="Minimal Node Size",
			 color="RMSE") +
	BerginskiRMisc::theme_berginski()

ggsave(here('figures/single_model_expression/rand_forest_more_tuning.png'),
			 more_rmse + more_r2,
			 height=3,width=6
)
BerginskiRMisc::trimImage(here('figures/single_model_expression/rand_forest_more_tuning.png'))
```


# 500 feature lots of tree counts

```{r}
model_tuning_results = data.frame()

for (feat_count in c(500)) {
	model_files = Sys.glob(here('results/single_model_expression_regression/rand_forest/',
															sprintf('%dfeat_notune_pred',feat_count),
															"*"))
	
	for (this_file in model_files) {
		these_cv_results = read_rds(this_file) %>%
			mutate(fold_file = basename(this_file),
						 feat_count = feat_count)
		
		model_tuning_results = bind_rows(
			model_tuning_results,
			data.frame(feat_count = feat_count,
								 tree_count = 500,
								 fold_file = basename(this_file),
								 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
								 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
	}
}

for (feat_count in c(500)) {
	for (tree_count in c(1,5,10,15,20,40,60,80,100,200,300,400)) {
		model_files = Sys.glob(here('results/single_model_expression_regression/rand_forest_tune/',
																sprintf('%dfeat_%dtrees_pred',feat_count,tree_count),
																"*"))
		
		for (this_file in model_files) {
			these_cv_results = read_rds(this_file) %>%
				mutate(fold_file = basename(this_file),
							 feat_count = feat_count)
			
			model_tuning_results = bind_rows(
				model_tuning_results,
				data.frame(feat_count = feat_count,
									 fold_file = basename(this_file),
									 tree_count = tree_count,
									 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
									 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
		}
	}
}

model_tuning_results_summary = model_tuning_results %>% 
	group_by(feat_count,tree_count) %>% 
	nest() %>%
	mutate(rmse = map(data, ~ tidy(t.test(.x$rmse)))) %>%
	mutate(r2 = map(data, ~ tidy(t.test(.x$r2)))) %>%
	unnest(cols=c(rmse,r2),names_sep = "_") %>%
	select(feat_count,tree_count,r2_estimate,rmse_estimate,everything())
```

```{r}
library(gghighlight)

ram_usage = read_csv(here('results/single_model_expression_regression/model_size_ram_usage.csv'))

default_results = model_tuning_results_summary %>%
	filter(tree_count == 500)

r2_plot = ggplot(model_tuning_results_summary,
								 aes(y=r2_estimate,x=as.factor(tree_count))) +
	geom_hline(aes(yintercept = default_results$r2_conf.low),alpha=0.25,lty = 2) +
	# geom_point() +
	geom_errorbar(aes(ymin=r2_conf.low,ymax=r2_conf.high), color = "blue") +
	gghighlight(tree_count == 100,
							unhighlighted_params = list(color = "black")) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	labs(x="Number of Trees",y="R\u00B2",color="# Trees") +
	BerginskiRMisc::theme_berginski()

rmse_plot = ggplot(model_tuning_results_summary,
									 aes(y=rmse_estimate,x=as.factor(tree_count))) +
	geom_hline(aes(yintercept = default_results$rmse_conf.high),alpha=0.25,lty = 2) +
	# geom_point() +
	geom_errorbar(aes(ymin=rmse_conf.low,ymax=rmse_conf.high), color = 'blue') +
	gghighlight(tree_count == 100, 
							unhighlighted_params = list(color = "black")) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	labs(x="Number of Trees",y="RMSE",color="# Trees") +
	BerginskiRMisc::theme_berginski()

ram_usage_plot = ggplot(ram_usage, aes(x=as.factor(tree_count),y = Peak_RAM_Used_MiB/1024)) + 
	geom_point(color = 'blue') +	
	gghighlight(tree_count == 100, 
							unhighlighted_params = list(color = "black")) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	labs(x="Number of Trees",y="Model RAM Usage (GB)") +
	BerginskiRMisc::theme_berginski()

ggsave(here('figures/single_model_expression/webapp_model_scaling.png'),
			 r2_plot + rmse_plot + ram_usage_plot, width=4.5*1.5, height=2.25)
BerginskiRMisc::trimImage(here('figures/single_model_expression/webapp_model_scaling.png'))
```

