---
title: "VIP Model Figures"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(vip)
library(tidymodels)
library(DarkKinaseTools)

knitr::opts_knit$set(root.dir = here())
```

```{r}
final_model <- read_rds(here('results/single_model_expression_regression/final_model_500feat.rds'))

gene_classifications = read_csv(here('data/KlaegerScience2017/manual_gene_labels.csv')) %>%
	bind_rows(all_kinases %>% select(symbol,class) %>% rename(gene_name = symbol)) %>% 
	#adding extra label for abbreviated activation name
	bind_rows(data.frame(gene_name = "CSNK2A(1/3)", class = "Light")) %>%
	distinct()

exp_interactor_type = read_rds(here('results/single_model_expression_regression/expression_feature_interactors.rds')) %>%
	mutate(Variable = paste0(type,"_",hgnc)) %>%
	mutate(interaction = case_when(
		direct_count >= 1 ~ "Direct",
		kinase_count >= 1 ~ "Kinase",
		T ~ "Neither"
	))
```

```{r}
all_importance = vi(final_model %>% extract_fit_parsnip()) %>%
		mutate(feature_type = case_when(
			str_detect(Variable, "^act_") ~ "Activation",
			str_detect(Variable, "^exp_") ~ "Expression",
			str_detect(Variable, "^dep_") ~ "Depmap",
			str_detect(Variable, "^cnv_") ~ "CNV",
			str_detect(Variable, "^prot_") ~ "Proteomics",
			T ~ Variable
		)) %>%
	mutate(Variable = ifelse(Variable == "act_CSNK2A1;CSNK2A3","act_CSNK2A(1/3)",Variable)) %>%
	extract(Variable, c(NA,"gene"),"(.*)_(.*)",remove=F) %>%
	left_join(gene_classifications, by=c('gene'='gene_name')) %>%
	left_join(exp_interactor_type %>% select(Variable,interaction)) %>%
	mutate(class = ifelse(is.na(class), "Non-kinase",class)) %>%
	arrange(Importance) %>%
	mutate(Variable = fct_inorder(Variable))

ggplot(all_importance %>% slice_tail(n = 25), 
			 aes(x=Importance,y=Variable,fill=class)) + 
	geom_col() +
	labs(y='',fill='',x='Feature Importance') +
	BerginskiRMisc::theme_berginski() +
	theme(legend.justification = c(1, 0), legend.position = c(1, 0)) +
	scale_fill_brewer(type='qual', palette = "Dark2")
ggsave(here('figures/single_model_expression/top_25_VIP.png'),width=5,height=3.75)
BerginskiRMisc::trimImage(here('figures/single_model_expression/top_25_VIP.png'))

ggplot(all_importance %>% 
			 	filter(feature_type == "Expression") %>%
			 	slice_tail(n = 25), 
			 aes(x=Importance,y=Variable, fill = interaction)) + 
	geom_col() +
	labs(y='',fill='Interaction\nType',x='Feature Importance') +
	BerginskiRMisc::theme_berginski() +
	scale_fill_brewer(type='qual', palette = "Set2")
ggsave(here('figures/single_model_expression/top_25_exp_VIP.png'),width=5,height=3.75)
BerginskiRMisc::trimImage(here('figures/single_model_expression/top_25_exp_VIP.png'))
```

```{r}
ggplot(all_importance, aes(x=feature_type,y=Importance)) + 
	geom_boxplot() +
	labs(x='',y='Feature Importance') +
	BerginskiRMisc::theme_berginski()
ggsave(here('figures/single_model_expression/importance_box.png'),width=2,height=3.75)
BerginskiRMisc::trimImage(here('figures/single_model_expression/importance_box.png'))
```