---
title: "Make CV Splits"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(tictoc)
library(doParallel)
library(patchwork)

knitr::opts_knit$set(root.dir = here())
```

# Load Data

```{r}
dir.create(here('results/single_model_expression_regression'), recursive = T)

klaeger_wide = read_rds(here('results/klaeger_full_tidy.rds')) %>%
	mutate(act_gene_name = paste0("act_",gene_name)) %>%
	select(-gene_name) %>%
	pivot_wider(names_from = act_gene_name, values_from = relative_intensity)

PRISM_klaeger_imputed = read_rds(here('results/PRISM_klaeger_imputed_tidy.rds'))

CCLE_data = read_rds(here('results/single_model/full_CCLE_expression_set_for_ML.rds'))

PRISM_klaeger_imputed = PRISM_klaeger_imputed %>%
	filter(depmap_id %in% CCLE_data$DepMap_ID) %>%
	ungroup()
```

# Feature Selection Functions

```{r}
find_feature_correlations <- function(row_indexes = NA) {
	if (is.na(row_indexes)) {
		row_indexes = 1:dim(PRISM_klaeger_imputed)[1]
	}
	
	##############################################################################
	# PRISM - Klaeger Activation Correlations
	##############################################################################
	PRISM_klaeger_cor = PRISM_klaeger_imputed %>%
		slice(row_indexes) %>%
		left_join(klaeger_wide, by = c('drug'='drug', 'klaeger_conc' = 'concentration_M')) %>%
		select(-depmap_id,-drug,-klaeger_conc) %>%
		identity()
	
	activation_cor = cor(PRISM_klaeger_cor %>% pull(imputed_viability), PRISM_klaeger_cor %>% select(-imputed_viability)) %>%
		as.data.frame() %>%
		pivot_longer(everything(), names_to = "feature",values_to = "cor")
	
	rm(PRISM_klaeger_cor)
	gc()
	
	##############################################################################
	# PRISM - CCLE Expression Correlations
	##############################################################################
	CCLE_cor = data.frame()
	
	CCLE_var_split = split(names(CCLE_data),c(1:10))
	
	for (i in 1:10) {
		PRISM_CCLE_cor = PRISM_klaeger_imputed %>%
			slice(row_indexes) %>%
			left_join(CCLE_data %>%
									select(c(CCLE_var_split[[i]],"DepMap_ID")),
								by=c('depmap_id' = 'DepMap_ID')) %>%
			select(-depmap_id,-drug,-klaeger_conc) %>%
			identity()
		
		this_CCLE_cor = cor(PRISM_CCLE_cor %>% pull(imputed_viability), PRISM_CCLE_cor %>% select(-imputed_viability)) %>%
			as.data.frame() %>%
			pivot_longer(everything(), names_to = "feature", values_to = "cor")
		
		CCLE_cor = bind_rows(
			CCLE_cor,
			this_CCLE_cor
		)
		
		rm(PRISM_CCLE_cor)
		gc()
		
	}
	
	all_cor = bind_rows(activation_cor, CCLE_cor) %>% 
		mutate(abs_cor = abs(cor)) %>% 
		arrange(desc(abs_cor)) %>% 
		mutate(rank = 1:n()) %>%
		mutate(feature_type = case_when(
			str_detect(feature, "^act_") ~ "Activation",
			str_detect(feature, "^exp_") ~ "Expression",
			str_detect(feature, "^dep_") ~ "Depmap",
			str_detect(feature, "^cnv_") ~ "CNV",
			str_detect(feature, "^prot_") ~ "Proteomics",
			T ~ feature
		))
	
	return(all_cor)
}
```

```{r}
build_regression_viability_set <- function(feature_cor, num_features) {
	
	activation_set = klaeger_wide %>% 
		select(any_of(feature_cor$feature[1:num_features]),'drug','concentration_M')
	
	CCLE_set = CCLE_data %>%
		select(any_of(feature_cor$feature[1:num_features]),'DepMap_ID')
	
	regression_viability = PRISM_klaeger_imputed %>%
		left_join(activation_set, by = c('drug'='drug', 'klaeger_conc' = 'concentration_M')) %>%
		left_join(CCLE_set, by=c('depmap_id' = 'DepMap_ID')) %>%
		mutate(target_viability = imputed_viability)
	
	return(regression_viability)
}
```

# Assess Full Data Correlations

```{r}
tic()
all_cor = find_feature_correlations()
toc()
```

```{r}
sd_set = bind_rows(
	apply(klaeger_wide %>% 
					select(contains("act_")),2,sd) %>% 
		as.data.frame() %>%
		rownames_to_column(var = "feature") %>%
		rename(sd = '.'),
	
	apply(CCLE_data %>%
					select(contains("exp_")),2,sd) %>%
		as.data.frame() %>%
		rownames_to_column(var = "feature") %>%
		rename(sd = '.')
)

cor_and_sd = all_cor %>%
	left_join(sd_set) %>%
	mutate(feature_type = case_when(
		str_detect(feature, "^act_") ~ "Activation",
		str_detect(feature, "^exp_") ~ "Expression",
		str_detect(feature, "^dep_") ~ "Depmap",
		str_detect(feature, "^cnv_") ~ "CNV",
		str_detect(feature, "^prot_") ~ "Proteomics",
		T ~ feature
	))

ggplot(cor_and_sd, aes(x=abs_cor,y=sd)) + 
	geom_hex() +
	geom_smooth() +
	BerginskiRMisc::theme_berginski() + 
	labs(x = "Absolute Value Correlation",y="Feature Standard Deviation") +
	facet_wrap(~feature_type, scales = "free")
ggsave(here('figures/feature_selection_expression/correlation_vs_sd.png'))
```

```{r}
only_act = cor_and_sd %>%
	filter(feature_type == "Activation")

act_only = ggplot(only_act, aes(x=abs_cor,y=sd)) + 
	geom_point() +
	geom_smooth() +
	labs(x = "Absolute Value Correlation",y="Feature Standard Deviation") +
	BerginskiRMisc::theme_berginski()

non_cor = ggplot(only_act %>% filter(is.na(abs_cor)), aes(y=sd,x=1)) + 
	geom_boxplot() +
	ylim(c(0.015,0.36)) +
	geom_jitter() +
	labs(y='',x='') +
	theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
				axis.title.y=element_blank()) +
	BerginskiRMisc::theme_berginski()

this_layout = "
AAAAB"

full_plot = act_only + non_cor + plot_layout(design = this_layout)
full_plot
ggsave(here('figures/feature_selection_expression/activation_cor_vs_sd.png'))
```

```{r}
per_group_rank = all_cor %>%
	group_by(feature_type) %>%
	nest() %>%
	mutate(group_rank = map(data, ~ .x %>% 
														mutate(sub_percent_rank = percent_rank(abs_cor*-1),
																	 sub_rank = 1:n()))) %>%
	unnest(cols = c(group_rank)) %>%
	ungroup() %>%
	select(feature,sub_rank,sub_percent_rank) %>%
	identity()

all_cor = all_cor %>%
	left_join(per_group_rank)
```

```{r}
dir.create(here('figures/feature_selection_expression'))
ggplot(all_cor, aes(x=abs_cor)) +
	geom_histogram() +
	BerginskiRMisc::theme_berginski() +
	labs(x="Absolute Value Correlation", y="Number of Features") +
	facet_wrap(~feature_type,scales = "free_y")

ggsave(here('figures/feature_selection_expression/feature_cor_histograms.png'),width=10)
BerginskiRMisc::trimImage(here('figures/feature_selection_expression/feature_cor_histograms.png'))
```

```{r}
ggplot(all_cor, aes(x=rank,y=sub_percent_rank,color=feature_type)) +
	geom_vline(aes(xintercept = 500),alpha = 0.25, linetype = 2) +
	geom_vline(aes(xintercept = 200),alpha = 0.25, linetype = 2) +
	geom_vline(aes(xintercept = 1000),alpha = 0.25, linetype = 2) +
	geom_vline(aes(xintercept = 1500),alpha = 0.25, linetype = 2) +
	geom_line() +
	labs(x="Feature Type Overall Correlation Rank",y="Percentile Sub Rank", color='') +
	BerginskiRMisc::theme_berginski()
ggsave(here('figures/feature_selection_expression/group_perc_rank.png'),width=6*0.75,height=5*0.75)
BerginskiRMisc::trimImage(here('figures/feature_selection_expression/group_perc_rank.png'))


ggplot(all_cor %>% filter(rank <= 2000), aes(x=rank,y=sub_percent_rank,color=feature_type)) +
	geom_vline(aes(xintercept = 500),alpha = 0.25, linetype = 2) +
	geom_vline(aes(xintercept = 200),alpha = 0.25, linetype = 2) +
	geom_vline(aes(xintercept = 1000),alpha = 0.25, linetype = 2) +
	geom_vline(aes(xintercept = 1500),alpha = 0.25, linetype = 2) +
	geom_line() +
	labs(x="Feature Type Overall Correlation Rank",y="Percentile Sub Rank", color='') +
	BerginskiRMisc::theme_berginski()
ggsave(here('figures/feature_selection_expression/group_perc_rank_zoom.png'),width=6*0.75,height=5*0.75)
BerginskiRMisc::trimImage(here('figures/feature_selection_expression/group_perc_rank_zoom.png'))
```

```{r}
ggplot(all_cor, aes(x=rank,y=sub_rank,color=feature_type)) +
	geom_vline(aes(xintercept = 500),alpha = 0.25, linetype = 2) +
	geom_vline(aes(xintercept = 200),alpha = 0.25, linetype = 2) +
	geom_vline(aes(xintercept = 1000),alpha = 0.25, linetype = 2) +
	geom_vline(aes(xintercept = 1500),alpha = 0.25, linetype = 2) +
	geom_line() +
	labs(x="Feature Type Overall Correlation Rank",y="Number of Features", color='') +
	BerginskiRMisc::theme_berginski()
ggsave(here('figures/feature_selection_expression/group_rank_count.png'),width=6*0.75,height=5*0.75)
BerginskiRMisc::trimImage(here('figures/feature_selection_expression/group_rank_count.png'))


ggplot(all_cor %>% filter(rank <= 2000), aes(x=rank,y=sub_rank,color=feature_type)) +
	geom_vline(aes(xintercept = 500),alpha = 0.25, linetype = 2) +
	geom_vline(aes(xintercept = 200),alpha = 0.25, linetype = 2) +
	geom_vline(aes(xintercept = 1000),alpha = 0.25, linetype = 2) +
	geom_vline(aes(xintercept = 1500),alpha = 0.25, linetype = 2) +
	geom_line() +
	labs(x="Feature Type Overall Correlation Rank",y="Number of Features", color='') +
	BerginskiRMisc::theme_berginski()
ggsave(here('figures/feature_selection_expression/group_rank_count_zoom.png'),width=6*0.75,height=5*0.75)
BerginskiRMisc::trimImage(here('figures/feature_selection_expression/group_rank_count_zoom.png'))
```

# Build Cross Validation Splits

```{r}
if (file.exists(here('results/single_model_expression_regression/CV_split_row_nums.rds'))) {
	fold_ids = read_rds(here('results/single_model_expression_regression/CV_split_row_nums.rds'))
} else {
	fold_ids = sample(rep(1:10,length.out = dim(PRISM_klaeger_imputed)[1]))
	write_rds(fold_ids, here('results/single_model_expression_regression/CV_split_row_nums.rds'))
}

rand_forest_grid <- data.frame(
	trees = seq(1000,5000,by=1000)
) %>% write_rds(here('results/single_model_expression_regression/hyper_param_search_space.rds'))
```

```{r}
if (! file.exists(here('results/single_model_expression_regression/full_model_data_set_1500feat.rds'))) {
	all_cor = find_feature_correlations()
	build_regression_viability_set(all_cor,1500) %>%
		write_rds(here('results/single_model_expression_regression/full_model_data_set_1500feat.rds'), compress='gz')
}
```

```{r}
tic()
for (i in 1:10) {
	splits = list()
	
	these_feature_cor = find_feature_correlations(row_indexes = which(fold_ids != i))
	
	# for (feature_num in c(200,500,1000,1500)) {
	for (feature_num in c(4000,5000,6000)) {
		target_dir = here('results/single_model_expression_regression/',sprintf('CV_splits_%sfeat',feature_num))
		dir.create(target_dir,recursive = T)
		
		splits[[1]] = make_splits(list("analysis" = which(fold_ids != i),"assessment" = which(fold_ids == i)),
															build_regression_viability_set(these_feature_cor,feature_num))
		
		id = sprintf("Fold%02d",i)
		
		cross_validation_set = new_rset(
			splits = splits,
			ids = id,
			attrib = sprintf("Per compound cv splits for fold ", i),
			subclass = c("vfold_cv", "rset")
		)	%>% write_rds(here(target_dir,sprintf('%02d.rds',i)), compress = 'gz')
		
	}
	
	print(paste0("Done with split: ",i))
}
toc()
```