---
title: "Prep CCLE Data for ML"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(vroom)
library(tictoc)
library(tidymodels)
library(DarkKinaseTools)
library(patchwork)

knitr::opts_knit$set(root.dir = here())
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 10)
```

# Loading CCLE Data Sets

```{r}
ccle_expression = vroom(here('data/CCLE_data/CCLE_expression.csv.gz')) %>% 
	rename(DepMap_ID = ...1)

ccle_CNV = vroom(here('data/CCLE_data/CCLE_gene_cn.csv.gz')) %>% 
	rename(DepMap_ID = ...1)

ccle_mutations = vroom(here('data/CCLE_data/CCLE_mutations.csv.gz'))

ccle_sample = vroom(here('data/CCLE_data/sample_info.csv.gz'))
```

# Prepping Data for ML

```{r}
ccle_expression %>%
  pivot_longer(-DepMap_ID, names_to = "gene_name", values_to = "log2_TPM") %>%
  extract(gene_name,c("Hugo_Symbol","NCBI"),regex = "(.*) \\((.*)\\)") %>% 
	select(-NCBI) %>%
	pivot_wider(names_from = Hugo_Symbol, values_from = log2_TPM, names_prefix = "exp_") %>%
	write_rds(here('results/single_model/full_CCLE_expression_set_for_ML.rds'), compress = 'gz')

ccle_CNV %>% pivot_longer(-DepMap_ID, names_to = "gene_name", values_to = "CNV_val") %>%
  extract(gene_name,c("Symbol","NCBI"),regex = "(.*) \\((.*)\\)") %>%	
	select(-NCBI) %>%
	pivot_wider(names_from = Symbol, values_from = CNV_val, names_prefix = "cnv_") %>%
	write_rds(here('results/single_model/full_CCLE_CNV_set_for_ML.rds'), compress = 'gz')
	
ccle_mutations %>%
	group_by(DepMap_ID,Hugo_Symbol) %>%
	summarise(has_deletorius = ifelse(any(isDeleterious), 1, 0)) %>%
	#This pivot_wider requires a values_fill because a majority of the values
	#aren't present in the list because most of the genes don't have any mutations
	#listed in the mutation collection. This indicates that there are no
	#mutations, so this should be encoded as a zero.
	pivot_wider(names_from = Hugo_Symbol, values_from = has_deletorius, names_prefix = "mut_", values_fill = 0) %>%
	write_rds(here('results/single_model/mutation_set_for_ML.rds'), compress = 'gz')
```