---
title: "Make CV Splits"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(tictoc)
library(doParallel)

knitr::opts_knit$set(root.dir = here())
```

```{r}
dir.create(here('results/single_model_plus_kinases/klaeger_CCLE_CV_splits/'), 
					 recursive = T)

klaeger_wide = read_rds(here('results/klaeger_full_tidy.rds')) %>%
	mutate(act_gene_name = paste0("act_",gene_name)) %>%
	select(-gene_name) %>%
	pivot_wider(names_from = act_gene_name, values_from = relative_intensity)

CCLE_expression = read_rds(here('results/single_model/expression_set_plus_kinase_for_ML.rds'))

PRISM_klaeger_imputed = read_rds(here('results/PRISM_klaeger_imputed_tidy.rds'))

PRISM_klaeger_CCLE = PRISM_klaeger_imputed %>%
	left_join(klaeger_wide, by = c('drug'='drug', 'klaeger_conc' = 'concentration_M')) %>%
	filter(depmap_id %in% CCLE_expression$DepMap_ID) %>%
	left_join(CCLE_expression, by=c('depmap_id' = 'DepMap_ID'))

median_viability = median(PRISM_klaeger_CCLE$imputed_viability)

binarized_viability = PRISM_klaeger_CCLE %>%
	mutate(target_viability_split = as.factor(imputed_viability < median_viability)) %>%
	write_rds(here('results/single_model_plus_kinases/klaeger_CCLE_binary_full.rds'), compress = 'gz')
```

```{r}
fold_ids = sample(rep(1:10,length.out = dim(binarized_viability)[1]))

for (i in 1:10) {
	splits = list()
	
	splits[[1]] = make_splits(list("analysis" = which(fold_ids != i),"assessment" = which(fold_ids == i)),
																binarized_viability)
	
	id = sprintf("Fold%02d",i)
	
	cell_line_compound_splits = new_rset(
		splits = splits,
		ids = id,
		attrib = sprintf("Per compound cv splits for fold ", i),
		subclass = c("vfold_cv", "rset")
	)	%>% write_rds(here('results/single_model_plus_kinases/klaeger_CCLE_CV_splits/',sprintf('%02d.rds',i)), compress = 'gz')
}
```