---
title: "Assess Classification Models"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(patchwork)
library(tictoc)
library(gt)

knitr::opts_knit$set(root.dir = here())
model_results = data.frame()
all_pred = data.frame()
```

# Rand Forest Model Baseline

```{r}
tic()

for (feat_count in c(100,200,300,400,500,600,700,800,900,1000,1500,2000)) {
	model_files = Sys.glob(here('results/single_model_expression_regression/rand_forest/',
															sprintf('%dfeat_notune_pred',feat_count),
															"*"))
	
	for (this_file in model_files) {
		these_cv_results = read_rds(this_file) %>%
			mutate(fold_file = basename(this_file),
						 feat_count = feat_count)
		
		model_results = bind_rows(
			model_results,
			data.frame(feat_count = feat_count,
								 trees = 500,
								 fold_file = basename(this_file),
								 data_set = 'exp_activation',
								 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
								 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
	}
	
}
toc()
```

# Rand Forest Model Exp Only

```{r}
# tic()
# 
# for (feat_count in c(100,200,300,400,500,600,700,800,900,1000,1500,2000)) {
# 	model_files = Sys.glob(here('results/single_model_exp_only_regression/rand_forest/',
# 															sprintf('%dfeat_notune_pred',feat_count),
# 															"*"))
# 	
# 	for (this_file in model_files) {
# 		these_cv_results = read_rds(this_file) %>%
# 			mutate(fold_file = basename(this_file),
# 						 feat_count = feat_count)
# 		
# 		model_results = bind_rows(
# 			model_results,
# 			data.frame(feat_count = feat_count,
# 								 trees = 500,
# 								 fold_file = basename(this_file),
# 								 data_set = 'exp_only',
# 								 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
# 								 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
# 	}
# 	
# }
# toc()
```
# Kinase Activation and Expression

```{r}
tic()

for (feat_count in c(100,200,300,400,500,1000,1500,2000)) {
	model_files = Sys.glob(here('results/single_model_exp_only_kin_regression/rand_forest/',
															sprintf('%dfeat_notune_pred',feat_count),
															"*"))
	
	for (this_file in model_files) {
		these_cv_results = read_rds(this_file) %>%
			mutate(fold_file = basename(this_file),
						 feat_count = feat_count)
		
		model_results = bind_rows(
			model_results,
			data.frame(feat_count = feat_count,
								 trees = 500,
								 fold_file = basename(this_file),
								 data_set = 'kinase_act',
								 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
								 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
	}
	
}
toc()
```

# Kinase Activation and Expression

```{r}
tic()

for (feat_count in c(100,200,300,400,500)) {
	model_files = Sys.glob(here('results/single_model_act_only_regression/rand_forest/',
															sprintf('%dfeat_notune_pred',feat_count),
															"*"))
	
	for (this_file in model_files) {
		these_cv_results = read_rds(this_file) %>%
			mutate(fold_file = basename(this_file),
						 feat_count = feat_count)
		
		model_results = bind_rows(
			model_results,
			data.frame(feat_count = feat_count,
								 trees = 500,
								 fold_file = basename(this_file),
								 data_set = "act_only",
								 rmse = sqrt(mean((these_cv_results$.pred - these_cv_results$target_viability)^2)),
								 r2 = glance(summary(lm(these_cv_results$.pred ~ these_cv_results$target_viability)))$r.squared))
	}
	
}
toc()
```


```{r}
model_summary = model_results %>% 
	group_by(feat_count,trees,data_set) %>% 
	nest() %>%
	mutate(rmse = map(data, ~ tidy(t.test(.x$rmse)))) %>%
	mutate(r2 = map(data, ~ tidy(t.test(.x$r2)))) %>%
	unnest(cols=c(rmse,r2),names_sep = "_") %>%
	mutate(data_set_FN = case_when(
		data_set == "exp_activation" ~ "Act Exp",
		data_set == "kinase_act" ~ "Kinase Act Exp",
		data_set == "exp_only" ~ "Exp",
		data_set == "act_only" ~ "Act"
	)) %>%
	select(feat_count,trees,data_set,r2_estimate,rmse_estimate,everything())

# model_summary = model_results %>% 
# 	group_by(feat_count,trees,model_type) %>% 
# 	nest() %>%
# 	mutate(rmse = map(data, ~ tidy(t.test(.x$rmse)))) %>%
# 	mutate(r2 = map(data, ~ tidy(t.test(.x$r2)))) %>%
# 	unnest(cols=c(rmse,r2),names_sep = "_") %>%
# 	mutate(data_set_FN = case_when(
# 		data_set == "exp_activation" ~ "Activation and Expression",
# 		data_set == "exp_only" ~ "Expression"
# 	)) %>%
# 	select(model_type,feat_count,trees,r2_estimate,rmse_estimate,everything())
```


```{r}
r2_plot = ggplot(model_summary, 
			 aes(y=r2_estimate,x=feat_count, color=data_set_FN, shape=data_set_FN)) + 
	geom_point(alpha=0.8) + 
	# geom_errorbar(aes(ymin=r2_conf.low,ymax=r2_conf.high)) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	labs(x="Number of Features",y="R\u00B2", color="",shape="") +
	BerginskiRMisc::theme_berginski()

rmse_plot = ggplot(model_summary, 
			 aes(y=rmse_estimate,x=feat_count, color=data_set_FN, shape=data_set_FN)) + 
	geom_point(alpha=0.8) + 
	# geom_errorbar(aes(ymin=rmse_conf.low,ymax=rmse_conf.high)) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	labs(x="Number of Features",y="RMSE",color="",shape="") +
	BerginskiRMisc::theme_berginski()

ggsave(here('figures/single_model_all_data_regression/model_comparison_with_exp_only.png'),
			 r2_plot + rmse_plot +
			 	plot_layout(guides = "collect") & 
			 	theme(legend.position = 'bottom', legend.margin=margin(0,0,0,0), legend.box.margin=margin(-10,-10,-10,-10)),
			 width=6*0.8,height=3*0.8)
BerginskiRMisc::trimImage(here('figures/single_model_all_data_regression/model_comparison_with_exp_only.png'))
```