---
title: "Make CV Splits"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(tictoc)
library(doParallel)
library(patchwork)

knitr::opts_knit$set(root.dir = here())
```

# Load Data

```{r}
dir.create(here('results/single_model_dose_regression'), recursive = T)

klaeger_wide = read_rds(here('results/klaeger_full_tidy.rds')) %>%
	mutate(act_gene_name = paste0("act_",gene_name)) %>%
	select(-gene_name) %>%
	pivot_wider(names_from = act_gene_name, values_from = relative_intensity) %>%
	mutate(act_concentration_M = concentration_M)

PRISM_klaeger_imputed = read_rds(here('results/PRISM_klaeger_imputed_tidy.rds'))

CCLE_data = read_rds(here('results/single_model/full_CCLE_expression_set_for_ML.rds'))

PRISM_klaeger_imputed = PRISM_klaeger_imputed %>%
	filter(depmap_id %in% CCLE_data$DepMap_ID) %>%
	ungroup()

source(here('src/build_ML_models_expression_regression/shared_feature_selection_functions.r'))
```

# Build Cross Validation Splits

```{r}
if (file.exists(here('results/single_model_dose_regression/CV_split_row_nums.rds'))) {
	fold_ids = read_rds(here('results/single_model_dose_regression/CV_split_row_nums.rds'))
} else {
	fold_ids = sample(rep(1:10,length.out = dim(PRISM_klaeger_imputed)[1]))
	write_rds(fold_ids, here('results/single_model_dose_regression/CV_split_row_nums.rds'))
}
```

```{r}
if (! file.exists(here('results/single_model_dose_regression/full_model_data_set_1500feat.rds'))) {
	all_cor = find_feature_correlations()
	write_rds(all_cor,here('results/single_model_dose_regression/full_data_cor.rds'))
	build_regression_viability_set(all_cor,1500) %>%
		write_rds(here('results/single_model_dose_regression/full_model_data_set_1500feat.rds'), compress='gz')
}
```

```{r}
tic()
if (file.exists(here('results/single_model_dose_regression/CV_set_correlations.rds'))) {
	feature_cor_sets = read_rds(here('results/single_model_dose_regression/CV_set_correlations.rds'))
} else {
	feature_cor_sets = list()
	for (i in 1:10) {
		splits = list()
		
		feature_cor_sets[[i]] = find_feature_correlations(row_indexes = which(fold_ids != i))
		
		print(paste0("Done with split: ",i))
	}
	write_rds(feature_cor_sets, 
						here('results/single_model_dose_regression/CV_set_correlations.rds'), 
						compress = 'gz')
}
toc()
```

```{r}
tic()
for (i in 1:10) {
	splits = list()
	
	these_feature_cor = feature_cor_sets[[i]]
	
	for (feature_num in c(50,100,150,200,300,400,500,1000,1500,2000)) {
		target_dir = here('results/single_model_dose_regression/',sprintf('CV_splits_%sfeat',feature_num))
		dir.create(target_dir,recursive = T)
		
		splits[[1]] = make_splits(list("analysis" = which(fold_ids != i),"assessment" = which(fold_ids == i)),
															build_regression_viability_set(these_feature_cor,feature_num))
		
		id = sprintf("Fold%02d",i)
		
		cross_validation_set = new_rset(
			splits = splits,
			ids = id,
			attrib = sprintf("Per compound cv splits for fold ", i),
			subclass = c("vfold_cv", "rset")
		)	%>% write_rds(here(target_dir,sprintf('%02d.rds',i)), compress = 'gz')
		
	}
	
	print(paste0("Done with split: ",i))
}
toc()
```