---
title: "Find KCGS-Klaeger Drug Matches"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(readxl)

knitr::opts_knit$set(root.dir = here())
```

```{r}
klaeger = read_rds(here('results/klaeger_full_tidy.rds'))

klaeger_match_set = data.frame(
	drug = sort(unique(trimws(klaeger$drug)))
) %>% mutate(lower_case_drug = tolower(drug)) %>%
	mutate(no_dash_drug = str_replace(drug,"-",""))

PRISM = read_csv(here('data/PRISM/secondary/secondary-screen-replicate-treatment-info.csv'))

PRISM_match_set = PRISM %>%
	select(broad_id, name) %>%
	mutate(name = trimws(name)) %>%
	unique() %>%
	filter(!is.na(name))

matches = klaeger_match_set %>% 
	left_join(PRISM_match_set, by = c('drug'='name')) %>%
	rename(reg_broad_id = broad_id) %>%
	left_join(PRISM_match_set, by = c('lower_case_drug'='name')) %>%
	rename(lower_broad_id = broad_id) %>%
	left_join(PRISM_match_set, by = c('no_dash_drug'='name')) %>%
	rename(no_dash_broad_id = broad_id) %>%
	mutate(broad_id = case_when(
		!is.na(reg_broad_id) ~ reg_broad_id,
		!is.na(lower_broad_id) ~ lower_broad_id,
		!is.na(no_dash_broad_id) ~ no_dash_broad_id,
		TRUE ~ "No Match"
	)) %>%
	filter(broad_id != "No Match") %>%
	identity()

klaeger_no_matches = klaeger_match_set %>%
	filter(!drug %in% matches$drug)

PRISM_no_matches = PRISM_match_set %>%
	filter(!broad_id %in% matches$broad_id)

write_csv(klaeger_no_matches, here('src/find_PRISM_klaeger_matches/no_clear_match_klaeger_drug_list.csv'))
write_csv(as.data.frame(PRISM_no_matches), here('src/find_PRISM_klaeger_matches/no_clear_match_PRISM_drug_list.csv'))
```

From here we opened each individual drug list file and manually matched the drug names, producing "manual_matches.csv". 

```{r}
manual_matches = read_csv(here('src/find_PRISM_klaeger_matches/manual_matches.csv'))

manual_matches = manual_matches %>%
	left_join(PRISM_match_set, by = c('PRISM_name'='name'))

combined_match_list = matches %>%
	mutate(manual_match_broad_id = NA) %>%
	# select(drug,broad_id) %>%
	bind_rows(manual_matches %>%
							select(-PRISM_name) %>%
							rename(drug = klaeger_drug, manual_match_broad_id = broad_id)) %>%
	mutate(broad_id = ifelse(is.na(broad_id), manual_match_broad_id, broad_id)) %>%
	select(everything(),manual_match_broad_id,broad_id) %>%
	write_csv(here('src/find_PRISM_klaeger_matches/klaeger_PRISM_match_list.csv'))

unmatched_klaeger = klaeger_match_set %>% 
		filter(! drug %in% combined_match_list$drug) %>% 
		select(drug) %>% 
		select(klaeger_drug = drug)
unmatched_PRISM = PRISM_match_set %>%
	filter(! broad_id %in% combined_match_list$broad_id)

write_csv(unmatched_klaeger,here('src/find_PRISM_klaeger_matches/unmatched_klaeger.csv'))
write_csv(unmatched_PRISM,here('src/find_PRISM_klaeger_matches/unmatched_PRISM.csv'))
```