---
title: "Search Space EDA"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidyHeatmap)

knitr::opts_knit$set(root.dir = here())
```

```{r}
full_CCLE_expression_set_for_ML <- readRDS(here("results/single_model/full_CCLE_expression_set_for_ML.rds"))

klaeger_full_tidy <- readRDS(here("results/klaeger_full_tidy.rds"))

PRISM_klaeger_imputed_tidy <- readRDS(here("results/PRISM_klaeger_imputed_tidy.rds")) %>%
	filter(depmap_id %in% unique(full_CCLE_expression_set_for_ML$DepMap_ID))
```

```{r}
all_combos = crossing(
	drug = unique(klaeger_full_tidy$drug),
	depmap_id = unique(full_CCLE_expression_set_for_ML$DepMap_ID)
) 

already_tested = PRISM_klaeger_imputed_tidy %>%
	select(drug, depmap_id) %>%
	unique() %>%
	mutate(tested = 1)

cell_line_compound_counts = PRISM_klaeger_imputed_tidy %>%
	select(drug,depmap_id) %>%
	unique() %>%
	group_by(depmap_id) %>%
	summarise(num_drugs = n()) %>%
	arrange(desc(num_drugs)) %>%
	mutate(depmap_id = fct_inorder(depmap_id)) %>%
	add_row(depmap_id = unique(full_CCLE_expression_set_for_ML$DepMap_ID)[!unique(full_CCLE_expression_set_for_ML$DepMap_ID) %in% unique(PRISM_klaeger_imputed_tidy$depmap_id)],
					num_drugs = 0) %>%	
	mutate(depmap_id_num = 1:n())

drug_line_compound_counts = PRISM_klaeger_imputed_tidy %>%
	select(drug,depmap_id) %>%
	unique() %>%
	group_by(drug) %>%
	summarise(num_lines = n()) %>%
	arrange(desc(num_lines)) %>%
	mutate(drug = fct_inorder(drug)) %>%
	add_row(drug = unique(klaeger_full_tidy$drug)[!unique(klaeger_full_tidy$drug) %in% unique(PRISM_klaeger_imputed_tidy$drug)],
					num_lines = 0) %>%
	mutate(drug_id_num = 1:n())

PRISM_repeats = read_rds(here('results/validation_results/HCC_PRISM_replication_screen.rds')) %>% 
	select(compound, cell_line) %>% 
	rename(drug = compound) %>%
	unique() %>%
	left_join(data.frame(depmap_id = c("ACH-000624"),
											 cell_line = c("HCC-1806"))) %>%
	select(-cell_line) %>%
	mutate(tested_PRISM_rep = 2)

validation = read_rds(here('results/validation_results/validation_screen.rds')) %>% 
	select(compound, cell_line) %>% 
	rename(drug = compound) %>%
	unique() %>%
	left_join(data.frame(depmap_id = c("ACH-000927","ACH-000624"),
											 cell_line = c("BT-474","HCC1806"))) %>%
	select(-cell_line) %>%
	mutate(tested_val = 3)

double_extrap = read_rds(here('results/validation_results/double_negative_validation_screen.rds')) %>% 
	select(compound, cell_line) %>% 
	rename(drug = compound) %>%
	unique() %>%
	left_join(data.frame(depmap_id = c("ACH-000017","ACH-001391"),
											 cell_line = c("SKBR3","SUM159"))) %>%
	select(-cell_line) %>%
	mutate(tested_double = 4)

all_combos = all_combos %>% 
	left_join(already_tested) %>%
	# left_join(PRISM_repeats) %>%
	# left_join(validation) %>%
	# left_join(double_extrap) %>%
	# mutate(tested = ifelse(! is.na(tested_PRISM_rep), tested_PRISM_rep, tested)) %>%
	# mutate(tested = ifelse(! is.na(tested_val), tested_val, tested)) %>%
	# mutate(tested = ifelse(! is.na(tested_double), tested_double, tested)) %>%
	# mutate(tested = ifelse(is.na(tested), 0, tested)) %>%
	mutate(tested = ifelse(is.na(tested), 0, 1)) %>%
	mutate(depmap_id = fct_relevel(depmap_id, as.character(cell_line_compound_counts$depmap_id))) %>%
	mutate(drug = fct_relevel(drug, as.character(drug_line_compound_counts$drug))) %>%
	# select(-tested_PRISM_rep,-tested_val,-tested_double) %>%
	identity()
```

```{r}
all_combos_extra = all_combos %>%
	left_join(cell_line_compound_counts %>% select(depmap_id, depmap_id_num)) %>%
	left_join(drug_line_compound_counts %>% select(drug, drug_id_num))

# border = bind_rows(
# 	data.frame(depmap_id_num = unique(all_combos_extra$depmap_id_num),
# 						 drug_id_num = 0,
# 						 tested = 2),
# 	data.frame(depmap_id_num = unique(all_combos_extra$depmap_id_num),
# 						 drug_id_num = max(all_combos_extra$drug_id_num)+1,
# 						 tested = 2),
# 	data.frame(drug_id_num = unique(all_combos_extra$drug_id_num),
# 						 depmap_id_num = 0,
# 						 tested = 2),
# 	data.frame(drug_id_num = unique(all_combos_extra$drug_id_num),
# 						 depmap_id_num = max(all_combos_extra$depmap_id_num)+1,
# 						 tested = 2)
# )

# all_combos_extra = bind_rows(
# 	all_combos_extra,
# 	border
# )

mean_tested = list(
	x = mean(all_combos_extra %>% filter(tested == 1) %>% pull(depmap_id_num)),
	y = mean(all_combos_extra %>% filter(tested == 1) %>% pull(drug_id_num))
)

mean_not_tested = list(
	x = mean(all_combos_extra %>% filter(tested == 0) %>% pull(depmap_id_num)),
	y = mean(all_combos_extra %>% filter(tested == 0) %>% pull(drug_id_num))
)

ggplot(all_combos_extra, aes(y=drug_id_num,x=depmap_id_num, fill = as.factor(tested), width=1, height=1)) +
	geom_tile() +
	scale_fill_manual(values = c("black","white","green","red","brown")) +
	theme_void() +
	coord_fixed() +
	theme(legend.position = "none") +
	annotate("text",x=mean_tested$x, y=mean_tested$y, 
					 label=paste0(signif(mean(all_combos_extra$tested),3)*100,"% Tested")) +
	annotate("text",x=mean_not_tested$x, y=mean_not_tested$y, 
					 label=paste0(signif(1-mean(all_combos_extra$tested),3)*100,"% Not Tested"), color='white') +
	theme(legend.position = "none")
ggsave(here('figures/single_model_expression/untested_feature_space.png'), dpi = 300, height=229*0.005, width=1379*0.005)
BerginskiRMisc::trimImage(here('figures/single_model_expression/untested_feature_space.png'))
system(paste("convert -bordercolor blue -border 2", 
						 here('figures/single_model_expression/untested_feature_space.png'),
						 here('figures/single_model_expression/untested_feature_space.png')))
```

```{r}
ggplot(all_combos_extra, aes(y=drug_id_num,x=depmap_id_num, fill = as.factor(tested), width=1, height=1)) +
	geom_tile() +
	scale_fill_manual(values = c("white","black","green","red","brown")) +
	theme_void() +
	coord_fixed() +
	theme(legend.position = "none") +
	annotate("text",x=mean_tested$x, y=mean_tested$y, 
					 label=paste0(signif(mean(all_combos_extra$tested),3)*100,"% Tested"), color='white') +
	annotate("text",x=mean_not_tested$x, y=mean_not_tested$y, 
					 label=paste0(signif(1-mean(all_combos_extra$tested),3)*100,"% Not Tested")) +
	theme(legend.position = "none")
ggsave(here('figures/single_model_expression/untested_feature_space_invert.png'), dpi = 300, height=229*0.005, width=1379*0.005)
BerginskiRMisc::trimImage(here('figures/single_model_expression/untested_feature_space_invert.png'))
system(paste("convert -bordercolor blue -border 2", 
						 here('figures/single_model_expression/untested_feature_space_invert.png'),
						 here('figures/single_model_expression/untested_feature_space_invert.png')))
```

# Adding Highlights for the Rest of the Figure?

```{r}
all_combos = crossing(
	drug = unique(klaeger_full_tidy$drug),
	depmap_id = unique(full_CCLE_expression_set_for_ML$DepMap_ID)
) 

PRISM_repeats = read_rds(here('results/validation_results/HCC_PRISM_replication_screen.rds')) %>% 
	select(compound, cell_line) %>% 
	rename(drug = compound) %>%
	unique() %>%
	left_join(data.frame(depmap_id = c("ACH-000624"),
											 cell_line = c("HCC-1806"))) %>%
	select(-cell_line) %>%
	mutate(tested_PRISM_rep = 2)

validation = read_rds(here('results/validation_results/validation_screen.rds')) %>% 
	select(compound, cell_line) %>% 
	rename(drug = compound) %>%
	unique() %>%
	left_join(data.frame(depmap_id = c("ACH-000927","ACH-000624"),
											 cell_line = c("BT-474","HCC1806"))) %>%
	select(-cell_line) %>%
	mutate(tested_val = 3)

double_extrap = read_rds(here('results/validation_results/double_negative_validation_screen.rds')) %>% 
	select(compound, cell_line) %>% 
	rename(drug = compound) %>%
	unique() %>%
	left_join(data.frame(depmap_id = c("ACH-000017","ACH-001391"),
											 cell_line = c("SKBR3","SUM159"))) %>%
	select(-cell_line) %>%
	mutate(tested_double = 4)

all_combos = all_combos %>% 
	left_join(already_tested) %>%
	left_join(PRISM_repeats) %>%
	left_join(validation) %>%
	left_join(double_extrap) %>%
	mutate(tested = ifelse(! is.na(tested_PRISM_rep), tested_PRISM_rep, tested)) %>%
	mutate(tested = ifelse(! is.na(tested_val), tested_val, tested)) %>%
	mutate(tested = ifelse(! is.na(tested_double), tested_double, tested)) %>%
	mutate(tested = ifelse(is.na(tested), 0, tested)) %>%

	mutate(depmap_id = fct_relevel(depmap_id, as.character(cell_line_compound_counts$depmap_id))) %>%
	mutate(drug = fct_relevel(drug, as.character(drug_line_compound_counts$drug))) %>%
	select(-tested_PRISM_rep,-tested_val,-tested_double) %>%
	identity()

all_combos_extra = all_combos %>%
	left_join(cell_line_compound_counts %>% select(depmap_id, depmap_id_num)) %>%
	left_join(drug_line_compound_counts %>% select(drug, drug_id_num))

ggplot(all_combos_extra, aes(y=drug_id_num,x=depmap_id_num, fill = as.factor(tested), width=1, height=1)) +
	geom_tile() +
	scale_fill_manual(values = c("white","black","green","red","brown")) +
	theme_void() +
	coord_fixed() +
	theme(legend.position = "none") +
	annotate("text",x=mean_tested$x, y=mean_tested$y, 
					 label=paste0(signif(mean(all_combos_extra$tested),3)*100,"% Tested"), color='white') +
	annotate("text",x=mean_not_tested$x, y=mean_not_tested$y, 
					 label=paste0(signif(1-mean(all_combos_extra$tested),3)*100,"% Not Tested")) +
	theme(legend.position = "none")
ggsave(here('figures/single_model_expression/untested_feature_space_invert_highlight.png'), dpi = 300, height=229*0.005, width=1379*0.005)
BerginskiRMisc::trimImage(here('figures/single_model_expression/untested_feature_space_invert_highlight.png'))
system(paste("convert -bordercolor blue -border 2", 
						 here('figures/single_model_expression/untested_feature_space_invert_highlight.png'),
						 here('figures/single_model_expression/untested_feature_space_invert_highlight.png')))
```