---
title: "Single Model Prediction Analysis"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(patchwork)

knitr::opts_knit$set(root.dir = here())
```

```{r}
prediction_results = read_rds(here('results/single_model/final_prediction_results.rds')) %>%
	ungroup()

sample_info = read_csv(here('data/CCLE_data/sample_info.csv.gz'))

avail_lines = sample_info %>% 
	filter(cell_line_name %in% c("SK-BR-3","MCF7","MDA-MB-436","HCC1806",
															 "MDA-MB-231","BT-474","SUM-149PT","SUM-159PT",
															 "SUM-229PE"))

prediction_results = prediction_results %>%
	left_join(sample_info %>% select(DepMap_ID, cell_line_name))
```

```{r}
avail_prediction_results = prediction_results %>%
	filter(DepMap_ID %in% avail_lines$DepMap_ID) %>%
	left_join(avail_lines %>% select(DepMap_ID, cell_line_name))
```

```{r}
get_interesting_pred_plots <- function(this_cell_line_name) {
	these_predictions = avail_prediction_results %>% 
		filter(cell_line_name == this_cell_line_name)
	
	these_summary = these_predictions %>%
		group_by(drug) %>%
		summarise(full_mean_pred = mean(mean_pred), pred_range = max(mean_pred) - min(mean_pred)) %>%
		arrange(desc(full_mean_pred))
	
	deadly_pred_set = these_predictions %>%
		mutate(drug = fct_relevel(drug,as.character(these_summary$drug))) %>%
		filter(drug %in% these_summary$drug[1:5])
	
	high_eff_plot = ggplot(deadly_pred_set, aes(x=log10(concentration_M), y=mean_pred,color=drug)) +
		geom_point() +
		geom_line() + 
		ylim(c(0,1)) +
		labs(x="Log 10 Compound Concentration (M)", 
				 y="Predicted Probability of\nViability Below Median",
				 color='',
				 title = paste0(this_cell_line_name, " High Effect")) +
		BerginskiRMisc::theme_berginski() + theme(legend.position="bottom")
	
	low_eff_set = these_predictions %>%
		mutate(drug = fct_relevel(drug,as.character(these_summary$drug))) %>%
		filter(drug %in% rev(these_summary$drug)[1:5])
	
	low_eff_plot = ggplot(low_eff_set, aes(x=log10(concentration_M), y=mean_pred,color=drug)) +
		geom_point() +
		geom_line() + 
		ylim(c(0,1)) +
		labs(x="Log 10 Compound Concentration (M)", 
				 y="Predicted Probability of\nViability Below Median",
				 color='',
				 title = paste0(this_cell_line_name, " Low Effect")) +
		BerginskiRMisc::theme_berginski() + theme(legend.position="bottom")
	
	range_sort = these_summary %>%
		arrange(desc(pred_range))
	
	range_pred_set = these_predictions %>%
		mutate(drug = fct_relevel(drug,as.character(range_sort$drug))) %>%
		filter(drug %in% range_sort$drug[1:5])
	
	high_range_plot = ggplot(range_pred_set, aes(x=log10(concentration_M), y=mean_pred,color=drug)) +
		geom_point() +
		geom_line() + 
		ylim(c(0,1)) +
		labs(x="Log 10 Compound Concentration (M)", 
				 y="Predicted Probability of\nViability Below Median",
				 color='',
				 title = paste0(this_cell_line_name, " High Range")) +
		BerginskiRMisc::theme_berginski() + theme(legend.position="bottom")
	
	
	all_plots = high_eff_plot + low_eff_plot + high_range_plot
}

for (this_line in unique(avail_prediction_results$cell_line_name)) {
	this_plot = get_interesting_pred_plots(this_line)
	ggsave(here('figures/single_model/avail_lines_predictions/',paste0(this_line,".png")), this_plot, width=15,height=5)
}
```

```{r}
line_diffs = avail_prediction_results %>%
	filter(cell_line_name == "SK-BR-3" | cell_line_name == "SUM-159PT") %>%
	select(-sd_pred,-DepMap_ID) %>% pivot_wider(names_from = cell_line_name, values_from = mean_pred) %>%
	mutate(diff = abs(`SK-BR-3` - `SUM-159PT`)) %>%
	group_by(drug) %>%
	summarise(mean_diff = mean(diff)) %>%
	arrange(desc(mean_diff))

line_diff_pred = avail_prediction_results %>%
	filter(cell_line_name == "SK-BR-3" | cell_line_name == "SUM-159PT", drug %in% line_diffs$drug[1:5])

ggplot(line_diff_pred, aes(x=log10(concentration_M), y=mean_pred,color=cell_line_name)) +
		geom_point() +
		geom_line() + 
		ylim(c(0,1)) +
		labs(x="Log 10 Compound Concentration (M)", 
				 y="Predicted Probability of\nViability Below 90%",
				 color='') +
		BerginskiRMisc::theme_berginski() +
	facet_wrap(~drug)
ggsave(here('figures/single_model/avail_lines_predictions/SK-BR_vs_SUM159.png'))
```


```{r}
deadly_pred_set = mda_predictions %>%
	mutate(drug = fct_relevel(drug,as.character(mda_summary$drug))) %>%
	filter(drug %in% mda_summary$drug[1:5])

ggplot(deadly_pred_set, aes(x=log10(concentration_M), y=mean_pred,color=drug)) +
	geom_point() +
	geom_line() + 
	ylim(c(0,1)) +
	labs(x="Log 10 Compound Concentration (M)", 
			 y="Predicted Probability of\nViability Below 90%",
			 color='') +
	BerginskiRMisc::theme_berginski()

ggsave(here('figures/mda_predictions_high_effect.png'),width=5,height=3)
```

```{r}
low_eff_set = mda_predictions %>%
	mutate(drug = fct_relevel(drug,as.character(mda_summary$drug))) %>%
	filter(drug %in% rev(mda_summary$drug)[1:5])

ggplot(low_eff_set, aes(x=log10(concentration_M), y=mean_pred,color=drug)) +
	geom_point() +
	geom_line() + 
	ylim(c(0,1)) +
	labs(x="Log 10 Compound Concentration (M)", 
			 y="Predicted Probability of\nViability Below 90%",
			 color='') +
	BerginskiRMisc::theme_berginski()

ggsave(here('figures/mda_predictions_low_effect.png'),width=5,height=3)
```

```{r}
range_sort = mda_summary %>%
	arrange(desc(pred_range))

range_pred_set = mda_predictions %>%
	mutate(drug = fct_relevel(drug,as.character(range_sort$drug))) %>%
	filter(drug %in% range_sort$drug[1:5])

ggplot(range_pred_set, aes(x=log10(concentration_M), y=mean_pred,color=drug)) +
	geom_point() +
	geom_line() + 
	ylim(c(0,1)) +
	labs(x="Log 10 Compound Concentration (M)", 
			 y="Predicted Probability of\nViability Below 90%",
			 color='') +
	BerginskiRMisc::theme_berginski()

ggsave(here('figures/mda_predictions_highest_range.png'),width=5,height=3)
```

# Cell Line Summaries

```{r}
all_line_summary = prediction_results %>% 
	group_by(cell_line_name,DepMap_ID,drug) %>%
	summarise(full_mean_pred = mean(mean_pred), pred_range = max(mean_pred) - min(mean_pred))


```