---
title: "Make Rand Forest Predictions"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidymodels)
library(here)
library(tictoc)
library(vip)

knitr::opts_knit$set(root.dir = here())
```

# Load Data

```{r}
# klaeger_wide = read_rds(here('results/klaeger_full_tidy.rds')) %>%
# 	pivot_wider(names_from = gene_name, values_from = relative_intensity)
# 
# CCLE_expression = read_rds(here('results/expression_set_for_ML.rds'))
# 
# PRISM_klaeger_imputed = read_rds(here('results/PRISM_klaeger_imputed_tidy.rds'))
# 
# PRISM_klaeger_CCLE = PRISM_klaeger_imputed %>%
# 	left_join(klaeger_wide, by = c('drug'='drug', 'klaeger_conc' = 'concentration_M')) %>%
# 	filter(depmap_id %in% CCLE_expression$DepMap_ID) %>%
# 	left_join(CCLE_expression, by=c('depmap_id' = 'DepMap_ID')) %>%
# 	select(-depmap_id,-drug,-klaeger_conc)

full_model_data_set = read_rds(here('results/single_model/klaeger_CCLE_binary_full.rds'))
```

# Build Models

```{r}
tic()

PRISM_klaeger_recipe = recipe(target_viability_split ~ ., full_model_data_set) %>%
	update_role(-starts_with("exp_"),-starts_with("act_"),-starts_with("target_"), new_role = "id variable") %>%
	prep()

rand_forest_spec <- rand_forest() %>% 
	set_engine("ranger", num.threads = parallel::detectCores() - 4,importance = "impurity") %>%
	set_mode("classification")

rand_forest_wf <- workflow() %>%
	add_model(rand_forest_spec) %>%
	add_recipe(PRISM_klaeger_recipe)

binary_model = rand_forest_wf %>%
	fit(full_model_data_set)

# if (file.exists(here('results/rand_forest_models.rds'))) {
# 	binary_models = read_rds(here('results/rand_forest_models.rds'))
# } else {
# 	binary_models
# 	
# 	for (this_depmap_id in unique(PRISM_klaeger_viability$depmap_id)) {
# 		this_config = rand_forest_best_params %>% filter(depmap_id == this_depmap_id)
# 		
# 
# 	}
# 	write_rds(binary_models,here('results/rand_forest_models.rds'), compress = 'gz')
# }

toc()
```

# VIP Data Summaries

```{r}
vip_data = data.frame()

for (this_depmap_id in names(binary_models)) {
	this_vip = binary_models[[this_depmap_id]] %>% vip(num_features = 1000)
	
	vip_data = vip_data %>%
		bind_rows(this_vip$data %>% mutate(depmap_id = this_depmap_id))
}

total_vip = vip_data %>% 
	group_by(Variable) %>% 
	summarise(summed_importance = sum(Importance)) %>%
	arrange(desc(summed_importance))
```

# Make Predictions

```{r}
tic()
binary_split_predictions = data.frame()

for (this_depmap_id in names(binary_models)) {
	tested_compounds = PRISM_klaeger_viability %>%
		filter(depmap_id == this_depmap_id) %>%
		pull(drug) %>%
		unique()
	
	untested_klaeger_set = klaeger_wide %>%
		filter(concentration_M != 0) %>%
		filter(!drug %in% tested_compounds)
	
	binary_split_predictions = binary_split_predictions %>%
		bind_rows(binary_models[[this_depmap_id]] %>%
								predict(untested_klaeger_set %>% select(-drug,-concentration_M), type='prob') %>%
								mutate(depmap_id = this_depmap_id, 
											 drug = untested_klaeger_set$drug,
											 concentration_M = untested_klaeger_set$concentration_M))
}
toc()

write_rds(binary_split_predictions,here('results/rand_forest_CL_model_predictions.rds'))
```
