---
title: "ALMANAC modelling with truncated klaeger vectors"
output: html_document
---
```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(tictoc)
library(doParallel)
library(patchwork)
library(ROCR)

knitr::opts_knit$set(root.dir = here())
```

```{r}
#read in data 
ALMANAC_klaeger_data = read_csv(here('results/ALMANAC_klaeger_data_for_ml_truncated_updated.csv'))
CCLE_data = read_rds(here('results/full_CCLE_expression_set_for_ML.rds'))

```

```{r}

#join in CCLE data 

ALMANAC_klaeger_CCLE_data = ALMANAC_klaeger_data %>% 
	left_join(CCLE_data, by = 'DepMap_ID') %>% 
	drop_na()

```


```{r}
#excluding viability > 1
model_data = ALMANAC_klaeger_CCLE_data %>% 
	filter(viability <=1)
	
model_data_long = model_data %>% 
	pivot_longer(starts_with(c('act', 'exp')), names_to = 'feature', values_to = 'value')

variable_genes = model_data_long %>% 
	group_by(feature) %>% 
	summarise(var = var(value)) %>% 
	filter(var > 0)

final_model_data = model_data %>% 
	select(CELLNAME, DepMap_ID, drug1, drug2, concentration_M_d1, concentration_M_d2, viability, any_of(variable_genes$feature))

# data_split <- initial_split(final_model_data, prop = 9/10)
# 
# train_data <- training(data_split)
# test_data  <- testing(data_split)


#continuous data feature selection 

find_feature_correlations <- function(row_indexes = NA, all_data) {
	if (is.na(row_indexes)) {
		row_indexes = 1:dim(all_data)[1]
	}
	
	all_cor = cor(
		all_data %>% pull(viability), all_data %>% select(starts_with(c('act', 'exp')))
		) %>%
		as.data.frame() %>%
		pivot_longer(everything(), names_to = "feature",values_to = "cor")
	
	
	all_correlations = all_cor %>% 
		mutate(abs_cor = abs(cor)) %>% 
		arrange(desc(abs_cor)) %>% 
		mutate(rank = 1:n()) %>%
		mutate(feature_type = case_when(
			str_detect(feature, "^act_") ~ "Activation",
			str_detect(feature, "^exp_") ~ "Expression",
			T ~ feature
		))

	return(all_correlations)	
}

feature_correlations = find_feature_correlations(all_data = final_model_data)

# feature_correlations %>% 
# 	filter(feature_type == 'Expression') %>% 
# 	ggplot(aes(x = abs_cor)) +
# 	geom_histogram()
# ggsave(here('figures/ALMANAC_modelling/truncated/Expression_correlations.png'))
# 
# feature_correlations %>% 
# 	filter(feature_type == 'Activation') %>% 
# 	ggplot(aes(x = abs_cor)) +
# 	geom_histogram()
# ggsave(here('figures/ALMANAC_modelling/truncated/Activation_correlations.png'))
# 
# model_data_long %>% 
# 	filter(str_detect(feature, "^exp_")) %>% 
# 	ggplot(aes(x = value)) +
# 	geom_histogram()
# ggsave(here('figures/ALMANAC_modelling/truncated/Expression_data_distribution.png'))
# 
# model_data_long %>% 
# 	filter(str_detect(feature, "^act_")) %>% 
# 	ggplot(aes(x = value)) +
# 	geom_histogram()
# ggsave(here('figures/ALMANAC_modelling/truncated/Activation_data_distribution.png'))

```

```{r}
#build classification model 10-fold CV

get_classification_fit = function(num_features, final_model_data) {
data = final_model_data %>% 
	select(any_of(feature_correlations$feature[1:num_features]),
					 CELLNAME, DepMap_ID, drug1, drug2, concentration_M_d1, concentration_M_d2, viability
					 ) %>% 
	mutate(viability_binary = as.factor(if_else(
		viability > median(viability),
		0,
		1
	))) %>% 
	select(-viability)

folds = vfold_cv(data, v = 10)

recipe = recipe(viability_binary ~ ., data) %>%
	update_role(-starts_with(c("act_", "exp_", "viability" )),
							new_role = "id variable")

rand_forest_spec <- rand_forest(
	trees = 500
) %>% set_engine("ranger") %>%
	set_mode("classification")

wflow <- 
  workflow() %>% 
  add_model(rand_forest_spec) %>% 
  add_recipe(recipe)

ctrl <- control_resamples(save_pred = TRUE)

fit <- 
  wflow %>% 
  fit_resamples(folds, control = ctrl)

return(fit)
}

fit_1500 = get_classification_fit(1500, final_model_data)
metrics_1500 = collect_metrics(fit_1500)
predictions_1500 = collect_predictions(fit_1500)

roc_curve = predictions_1500 %>%
	roc_curve(truth = viability_binary, .pred_0) %>%
	autoplot() + 
	ggtitle(round(metrics_1500$mean[2], 4))


pr_curve = predictions_1500 %>%
	pr_curve(truth = viability_binary, .pred_0) %>%
	autoplot() +
	ggtitle(round(metrics_1500$mean[1], 4))

c = roc_curve + pr_curve + plot_annotation(title = '10-fold CV ALMANAC Classification Model Results',
																					 subtitle = 'Classify Viability Below Median')

ggsave(here('figures/ALMANAC_truncated_classification_model_results_1500_features.png'))

fit_2000 = get_classification_fit(2000, final_model_data)
metrics_2000 = collect_metrics(fit_2000)
predictions_2000 = collect_predictions(fit_2000)

roc_curve = predictions_2000 %>%
	roc_curve(truth = viability_binary, .pred_0) %>%
	autoplot() + 
	ggtitle(round(metrics_2000$mean[2], 4))


pr_curve = predictions_2000 %>%
	pr_curve(truth = viability_binary, .pred_0) %>%
	autoplot() +
	ggtitle(round(metrics_2000$mean[1], 4))

c = roc_curve + pr_curve + plot_annotation(title = '10-fold CV ALMANAC Classification Model Results',
																					 subtitle = 'Classify Viability Below Median')

ggsave(here('figures/ALMANAC_modelling/truncated/ALMANAC_truncated_classification_model_results_2000_features.png'))

fit_2500 = get_classification_fit(2500, final_model_data)
metrics_2500 = collect_metrics(fit_2500)
predictions_2500 = collect_predictions(fit_2500)

roc_curve = predictions_2500 %>%
	roc_curve(truth = viability_binary, .pred_0) %>%
	autoplot() + 
	ggtitle(round(metrics_2500$mean[2], 4))

pr_curve = predictions_2500 %>%
	pr_curve(truth = viability_binary, .pred_0) %>%
	autoplot() +
	ggtitle(round(metrics_2500$mean[1], 4))

c = roc_curve + pr_curve + plot_annotation(title = '10-fold CV ALMANAC Classification Model Results',
																					 subtitle = 'Classify Viability Below Median')

ggsave(here('figures/ALMANAC_modelling/truncated/ALMANAC_truncated_classification_model_results_2500_features.png'))


```

```{r}
#build regression model 10-fold CV

data_2000_continuous = final_model_data %>% 
	select(any_of(feature_correlations$feature[1:2000]),
					 CELLNAME, DepMap_ID, drug1, drug2, concentration_M_d1, concentration_M_d2, viability
					 )

folds = vfold_cv(data_2000_continuous, v = 10)

feat2000_recipe = recipe(viability ~ ., data_2000_continuous) %>%
	update_role(-starts_with(c("act_", "exp_", "viability" )),
							new_role = "id variable")

rand_forest_spec <- rand_forest(
	trees = 500
) %>% set_engine("ranger") %>%
	set_mode("regression")

feat2000_wflow <- 
  workflow() %>% 
  add_model(rand_forest_spec) %>% 
  add_recipe(feat2000_recipe)

ctrl <- control_resamples(save_pred = TRUE)

reg_fit <- 
  feat2000_wflow %>% 
  fit_resamples(folds, control = ctrl)

cv_metrics_regression = collect_metrics(reg_fit)

predictions_regression = collect_predictions(reg_fit) %>% 
	rename('predicted_viability' = .pred)

predictions_regression %>% 
	ggplot(aes(x = viability, y = predicted_viability)) +
	geom_hex() +
	scale_fill_gradient(low="lightblue1",high="darkblue",trans="log10") +
	geom_smooth() +
	labs(title = paste0('Correlation = ', 
											round(
												cor(predictions_regression$viability, 
														predictions_regression$predicted_viability),
												4),
											', R-Squared = ', round(
												cv_metrics_regression$mean[2],
												4),
											', RMSE = ', round(cv_metrics_regression$mean[1],
																				 4))) + 
	geom_abline(intercept = 0, slope = 1, size = 0.5, colour = 'red') +
	xlim(0,1) +
	ylim(0,1)


ggsave(here('figures/ALMANAC_modelling/truncated/ALMANAC_truncated_regression_model_results.png'))
```