---
title: "Make Rand Forest Predictions"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidymodels)
library(here)
library(tictoc)
library(vip)

knitr::opts_knit$set(root.dir = here())
```

# Load Data for Model Building

```{r}
full_model_data_set = read_rds(here('results/single_model_via_50/klaeger_CCLE_binary_full.rds'))
```

# Organize Data for Predictions

```{r}
CCLE_expression_set = read_rds(here('results/single_model/full_CCLE_expression_set_for_ML.rds')) 

klaeger_wide = read_rds(here('results/klaeger_full_tidy.rds')) %>%
	mutate(act_gene_name = paste0("act_",gene_name)) %>%
	select(-gene_name) %>%
	pivot_wider(names_from = act_gene_name, values_from = relative_intensity) %>%
	filter(concentration_M != 0)

all_combinations = crossing(DepMap_ID = unique(CCLE_expression_set$DepMap_ID), 
														drug = unique(klaeger_wide$drug), 
														concentration_M = unique(klaeger_wide$concentration_M))

already_tested_combinations = full_model_data_set %>%
	select(depmap_id,drug,klaeger_conc) %>%
	rename(DepMap_ID = depmap_id,concentration_M = klaeger_conc)

not_tested_combinations = all_combinations %>% 
	anti_join(already_tested_combinations) %>%
	left_join(CCLE_expression_set) %>%
	left_join(klaeger_wide) %>%
	mutate(imputed_viability = NA,depmap_id = NA, klaeger_conc = NA)
```

# Build Models and Collect Predictions

I noticed some instability in the VIP plots of a few model draws, so I've decided to ensemble 10 model draws for the final prediction set.

```{r}
tic()

dir.create(here('results/single_model_via_50/final_models/'), showWarnings = F, recursive = T)
dir.create(here('results/single_model_via_50/final_prediction_sets/'), showWarnings = F, recursive = T)

for (i in 1:10) {
	
	PRISM_klaeger_recipe = recipe(target_viability_split ~ ., full_model_data_set) %>%
		update_role(-starts_with("exp_"),-starts_with("act_"),-starts_with("target_"), new_role = "id variable") %>%
		prep()
	
	rand_forest_spec <- rand_forest(
		trees = 4546,
		mtry = 1,
		min_n = 35
	) %>% 
		set_engine("ranger", num.threads = parallel::detectCores() - 2,importance = "impurity") %>%
		set_mode("classification")
	
	rand_forest_wf <- workflow() %>%
		add_model(rand_forest_spec) %>%
		add_recipe(PRISM_klaeger_recipe)
	
	binary_model = rand_forest_wf %>%
		fit(full_model_data_set) %>%
		write_rds(here('results/single_model_via_50/final_models',sprintf('model_%02d.rds',i)), compress = 'gz')
	
	chunk_size = floor(dim(not_tested_combinations)[1]/10)
	
	for (pred_part in 1:10) {
		if (pred_part != 10) {
			this_chunk = not_tested_combinations[((pred_part - 1)*chunk_size + 1):(pred_part*chunk_size),]
		} else {
			this_chunk = not_tested_combinations[((pred_part - 1)*chunk_size + 1):dim(not_tested_combinations)[1],]
		}
		
		binary_model %>%
			predict(this_chunk, type='prob') %>%
			select(-.pred_FALSE) %>%
			mutate(DepMap_ID = as.factor(this_chunk$DepMap_ID),
						 drug = as.factor(this_chunk$drug),
						 concentration_M = this_chunk$concentration_M) %>%
			write_rds(here('results/single_model_via_50/final_prediction_sets/',sprintf('set_%02d_part_%02d.rds',i,pred_part)), compress = 'gz')
		print(paste0("Done with model ",i," part ", pred_part))
	}
}

toc()
```

# Summarize Predictions to Final Set

```{r}
prediction_results = data.frame()
for (i in 1:10) {
	for (pred_part in 1:10) {
		prediction_results = bind_rows(
			prediction_results,
			read_rds(here('results/single_model_via_50/final_prediction_sets/',sprintf('set_%02d_part_%02d.rds',i,pred_part))) %>%
				mutate(pred_set = i)
		)
	}
		
}

final_predictions = prediction_results %>%
	group_by(DepMap_ID,drug,concentration_M) %>%
	summarise(mean_pred = mean(.pred_TRUE),sd_pred = sd(.pred_TRUE)) %>%
	write_rds(here('results/single_model_via_50/final_prediction_results.rds'), compress = 'gz')
```





```{r}
full_VIP_results = data.frame()

for (i in 1:1) {
	this_model = read_rds(here('results/single_model_via_50/final_models',sprintf('model_%02d.rds',i)))
	
	this_vip = vip(this_model$fit$fit, num_features = 5000)
	
	full_VIP_results = bind_rows(
		full_VIP_results,
		this_vip$data %>% mutate(model_run = i, rank = 1:n())
	)
}

full_VIP_results = full_VIP_results %>% 
	group_by(Variable) %>% 
	summarise(mean_imp = mean(Importance)) %>% 
	arrange(desc(mean_imp)) %>% 
	mutate(rank = 1:n())
```
