---
title: "Assess Classification Models"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(patchwork)
library(tictoc)
library(gt)

knitr::opts_knit$set(root.dir = here())
model_results = data.frame()
all_pred = data.frame()
```

# Rand Forest Model Assessment


```{r}
tic()

for (feat_count in c(50,100,150,200,300,400,500,1000,1500,2000,3000,4000,5000)) {
	
	for (hyper in 1:1) {
		model_files = Sys.glob(here('results/single_model_expression_regression',
																sprintf('rand_forest_param_scan_%dfeat_notune',feat_count),
																sprintf('hyper%03d*.rds', hyper)))
		
		if (length(model_files) != 10) {
			next;
		}
		
		for (i in 1:length(model_files)) {
			this_cv_data = read_rds(model_files[i]) %>%
				collect_predictions()
			
			all_pred = bind_rows(
				all_pred,
				this_cv_data %>% mutate(feat_count = feat_count, 
																trees = 500, 
																model_type = 'rand_forest')
			)
			
			model_results = bind_rows(
				model_results,
				data.frame(feat_count = feat_count,
									 hyper = i,
									 trees = 500,
									 model_type = 'rand_forest',
									 rmse = sqrt(mean((this_cv_data$.pred - this_cv_data$target_viability)^2)),
									 r2 = glance(summary(lm(this_cv_data$.pred ~ this_cv_data$target_viability)))$r.squared,
									 data_set = "exp"))
		}
	}
	
}

toc()
```

```{r}
tic()

for (feat_count in c(50,100,150,200,300,400,500,1000,1500,2000,3000,4000,5000)) {
	
	for (hyper in 1:1) {
		model_files = Sys.glob(here('results/single_model_all_data_regression',
																sprintf('rand_forest_param_scan_%dfeat_notune',feat_count),
																sprintf('hyper%03d*.rds', hyper)))
		
		if (length(model_files) != 10) {
			next;
		}
		
		for (i in 1:length(model_files)) {
			this_cv_data = read_rds(model_files[i]) %>%
				collect_predictions()
			
			all_pred = bind_rows(
				all_pred,
				this_cv_data %>% mutate(feat_count = feat_count, 
																trees = 500, 
																model_type = 'rand_forest')
			)
			
			model_results = bind_rows(
				model_results,
				data.frame(feat_count = feat_count,
									 hyper = i,
									 trees = 500,
									 model_type = 'rand_forest',
									 rmse = sqrt(mean((this_cv_data$.pred - this_cv_data$target_viability)^2)),
									 r2 = glance(summary(lm(this_cv_data$.pred ~ this_cv_data$target_viability)))$r.squared,
									 data_set = "all"))
		}
	}
	
}

toc()
```

```{r}
model_summary = model_results %>% 
	group_by(feat_count,trees,model_type,data_set) %>% 
	nest() %>%
	mutate(rmse = map(data, ~ tidy(t.test(.x$rmse)))) %>%
	mutate(r2 = map(data, ~ tidy(t.test(.x$r2)))) %>%
	unnest(cols=c(rmse,r2),names_sep = "_") %>%
	mutate(model_type_FN = case_when(
		model_type == "rand_forest" ~ "Random Forest",
		model_type == "xgboost" ~ "XGBoost",
		model_type == "lin" ~ "Linear Regresssion"
	)) %>%
	mutate(data_set_FN = case_when(
		data_set == "exp" ~ "Activation and Expression",
		data_set == "all" ~ "All Data"
	)) %>%
	select(model_type,feat_count,trees,r2_estimate,rmse_estimate,everything())
```


```{r}
r2_plot = ggplot(model_summary, 
			 aes(y=r2_estimate,x=feat_count, color=data_set_FN, shape=data_set_FN)) + 
	geom_point(alpha=0.8) + 
	# geom_errorbar(aes(ymin=r2_conf.low,ymax=r2_conf.high)) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	labs(x="Number of Features",y="R\u00B2", color="",shape="") +
	BerginskiRMisc::theme_berginski()

rmse_plot = ggplot(model_summary, 
			 aes(y=rmse_estimate,x=feat_count, color=data_set_FN, shape=data_set_FN)) + 
	geom_point(alpha=0.8) + 
	# geom_errorbar(aes(ymin=rmse_conf.low,ymax=rmse_conf.high)) +
	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
	labs(x="Number of Features",y="RMSE",color="",shape="") +
	BerginskiRMisc::theme_berginski()

ggsave(here('figures/single_model_all_data_regression/model_comparison.png'),
			 r2_plot + rmse_plot +
			 	plot_layout(guides = "collect") & 
			 	theme(legend.position = 'bottom', legend.margin=margin(0,0,0,0), legend.box.margin=margin(-10,-10,-10,-10)),
			 width=6*0.8,height=3*0.8)
BerginskiRMisc::trimImage(here('figures/single_model_all_data_regression/model_comparison.png'))
notifysendR::notify_send("done with plotting")
```

```{r}
# gt(model_results %>% arrange(feat_count,trees,rmse)) %>% 
# 	gtsave(here('figures/single_model_all_data_regression/model_results.png'))
# 
# all_pred = all_pred %>% mutate(bin_viability = cut(target_viability,breaks=seq(0,2,by=0.1),include.lowest=T))
# 
# all_pred_summary = all_pred %>%
# 	group_by(feat_count,bin_viability,trees) %>%
# 	summarise(median_via = median(target_viability),
# 						count = n())
# 
# ggplot(all_pred %>% filter(trees == 500), aes(x=bin_viability,y=.pred)) + 
# 	geom_boxplot(outlier.size = 0) + 
# 	geom_point(data = all_pred_summary, mapping = aes(x=bin_viability,y=median_via), color='blue') +
# 	theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
# 	BerginskiRMisc::theme_berginski() +
# 	labs(x="Binned Actual Viability",y="Predicted Viability") +
# 	facet_wrap(~feat_count)
# 
# ggsave(here('figures/single_model_all_data_regression/viability_vs_pred_notune_binned.png'),width=6, height=7)
# 
# 
# dir.create(here('figures/single_model_all_data_regression/param_tuning'))
# for (this_feat_count in c(200,500,1000,1500)) {
# 	temp = all_pred %>% filter(feat_count == this_feat_count)
# 	ggplot(temp, aes(x=bin_viability,y=.pred)) + 
# 		geom_boxplot(outlier.size = 0) + 
# 		geom_point(data = all_pred_summary %>% filter(feat_count == this_feat_count), 
# 							 mapping = aes(x=bin_viability,y=median_via), color='blue') +
# 		theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
# 		BerginskiRMisc::theme_berginski() +
# 		labs(x="Binned Actual Viability",y="Predicted Viability") +
# 		facet_wrap(~trees)
# 	
# 	ggsave(here('figures/single_model_all_data_regression/param_tuning',sprintf('feat_count%d_binned.png',this_feat_count)),width=6, height=7)
# }
```