---
title: "Make CV Splits"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(tictoc)
library(doParallel)

knitr::opts_knit$set(root.dir = here())
```

```{r}
dir.create(here('results/single_model_all_data_regression'), recursive = T)

source(here('src/build_ML_models_all_data_regression/shared_features_selection.R'))

klaeger_wide = read_rds(here('results/klaeger_full_tidy.rds')) %>%
	mutate(act_gene_name = paste0("act_",gene_name)) %>%
	select(-gene_name) %>%
	pivot_wider(names_from = act_gene_name, values_from = relative_intensity)

PRISM_klaeger_imputed = read_rds(here('results/PRISM_klaeger_imputed_tidy.rds'))
PRISM_IDs = unique(PRISM_klaeger_imputed$depmap_id)

depmap_data = read_rds(here('results/single_model/full_depmap_for_ML.rds'))

CCLE_data = read_rds(here('results/single_model/full_CCLE_expression_set_for_ML.rds'))

CNV_data = read_rds(here('results/single_model/full_CCLE_CNV_set_for_ML.rds'))

proteomics_data = read_csv(here('data/CCLE_data/CCLE_proteomics_imputed_wide.csv.gz')) %>%
	select(-CCLE_cell_line_name,-tenplex_number) %>% 
	rename_with( ~ paste0("prot_", .x), -DepMap_ID)

PRISM_klaeger_imputed = PRISM_klaeger_imputed %>%
	filter(depmap_id %in% depmap_data$DepMap_ID) %>%
	filter(depmap_id %in% CCLE_data$DepMap_ID) %>%
	filter(depmap_id %in% CNV_data$DepMap_ID) %>%
	filter(depmap_id %in% proteomics_data$DepMap_ID) %>%
	ungroup()
```

```{r}
duplicated_prot = proteomics_data %>% 
	filter(DepMap_ID == "ACH-000212" | DepMap_ID == "ACH-000680" | DepMap_ID == "ACH-000997")

all_ids_temp = data.frame(data_source = "PRISM",depmap_id = PRISM_IDs) %>%
	add_row(depmap_id = depmap_data %>% filter(DepMap_ID %in% PRISM_IDs) %>% pull(DepMap_ID),
					data_source = "DepMap") %>%
	add_row(depmap_id = CCLE_data %>% filter(DepMap_ID %in% PRISM_IDs) %>% pull(DepMap_ID),
					data_source = "Gene Exp") %>%
	add_row(depmap_id = CNV_data %>% filter(DepMap_ID %in% PRISM_IDs) %>% pull(DepMap_ID),
					data_source = "CNV") %>%
	add_row(depmap_id = proteomics_data %>% filter(DepMap_ID %in% PRISM_IDs) %>% pull(DepMap_ID) %>% unique(),
					data_source = "Proteomics") 

all_ids = all_ids_temp %>%
	group_by(depmap_id) %>%
	summarize(data_sources = list(as.factor(data_source)))

upset_plot = all_ids %>% 
	ggplot(aes(x=data_sources)) + 
	geom_bar() + 
	scale_x_upset(n_intersections = 10000) +
	labs(x="", y="Number of Cell Lines") +
	BerginskiRMisc::theme_berginski()

ggsave(here('figures/single_model_all_data_regression/cell_line_overlap_upset.png'),
			 upset_plot, height=5,width=5)
BerginskiRMisc::trimImage(here('figures/single_model_all_data_regression/cell_line_overlap_upset.png'))

# all_ids = data.frame(
# 	data_source = "PRISM", depmap_ids = list(c(PRISM_IDs))
# ) 
# %>%
# 	add_row(data_source = "DepMap", depmap_ids = list(c(depmap_data %>% filter(DepMap_ID %in% PRISM_IDs) %>% pull(DepMap_ID) %>% unique())))

```

```{r}
if (file.exists(here('results/single_model_all_data_regression/CV_split_row_nums.rds'))) {
	fold_ids = read_rds(here('results/single_model_all_data_regression/CV_split_row_nums.rds'))
} else {
	fold_ids = sample(rep(1:10,length.out = dim(PRISM_klaeger_imputed)[1]))
	write_rds(fold_ids, here('results/single_model_all_data_regression/CV_split_row_nums.rds'))
}

rand_forest_grid <- data.frame(
	trees = seq(1000,5000,by=1000)
) %>% write_rds(here('results/single_model_all_data_regression/hyper_param_search_space.rds'))
```

```{r}
tic()
if (file.exists(here('results/single_model_all_data_regression/CV_set_correlations.rds'))) {
	feature_cor_sets = read_rds(here('results/single_model_all_data_regression/CV_set_correlations.rds'))
} else {
	feature_cor_sets = list()
	for (i in 1:10) {
		splits = list()
		
		feature_cor_sets[[i]] = find_feature_correlations(row_indexes = which(fold_ids != i))
		
		print(paste0("Done with split: ",i))
	}
	write_rds(feature_cor_sets, 
						here('results/single_model_all_data_regression/CV_set_correlations.rds'), 
						compress = 'gz')
}
toc()
```

```{r}
tic()
for (i in 1:10) {
	splits = list()
	
	these_feature_cor = feature_cor_sets[[i]]
	
	for (feature_num in c(50,100,150,200,300,400,500,1000,1500,2000,3000,4000,5000)) {
		target_dir = here('results/single_model_all_data_regression/',sprintf('CV_splits_%sfeat',feature_num))
		dir.create(target_dir,recursive = T,showWarnings = F)
		
		this_regression_via_set = build_regression_viability_set(these_feature_cor,feature_num)
		
		splits[[1]] = make_splits(list("analysis" = which(fold_ids != i),"assessment" = which(fold_ids == i)),
															this_regression_via_set)
		
		id = sprintf("Fold%02d",i)
		
		cross_validation_set = new_rset(
			splits = splits,
			ids = id,
			attrib = sprintf("Per compound cv splits for fold ", i),
			subclass = c("vfold_cv", "rset")
		)	%>% write_rds(here(target_dir,sprintf('%02d.rds',i)), compress = 'gz')
		
	}
	
	print(paste0("Done with split: ",i))
}
toc()
```