---
title: "NEW ANALYSIS NAME"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)

knitr::opts_knit$set(root.dir = here())
```

```{r}
binary_split_predictions = read_rds(here('results/rand_forest_CL_model_predictions.rds'))
sample_info = read_csv(here('data/PRISM/sample_info.csv'))
```

```{r}
bc_predictions = binary_split_predictions %>%
	left_join(sample_info %>% select(DepMap_ID, cell_line_name, primary_disease), by=c('depmap_id'='DepMap_ID')) %>%
	filter(primary_disease == "Breast Cancer")

compound_counts = bc_predictions %>% 
	select(cell_line_name,drug) %>%
	unique() %>%
	count(drug) %>% 
	arrange(desc(n))

completely_untested_compounds = compound_counts %>%
	filter(n == max(n))
```

```{r}
not_triple_neg_predictions = binary_split_predictions %>%
	left_join(sample_info %>% 
							select(DepMap_ID, cell_line_name, primary_disease, lineage_sub_subtype), 
						by=c('depmap_id'='DepMap_ID')) %>%
	filter(primary_disease == "Breast Cancer", lineage_sub_subtype != "ERneg_HER2neg")

not_triple_neg_summary = not_triple_neg_predictions %>%
	group_by(drug,concentration_M) %>%
	summarise(mean_pred = mean(.pred_TRUE),
						count = n())
```

```{r}
triple_neg_lines = sample_info %>%
	filter(lineage_sub_subtype == "ERneg_HER2neg")

triple_neg_predictions = binary_split_predictions %>%
	filter(depmap_id %in% triple_neg_lines$DepMap_ID) %>%
	left_join(sample_info %>% select(DepMap_ID, cell_line_name), by=c('depmap_id'='DepMap_ID'))
```

# MDA-MB-231 Compound Assessement

```{r}
mda_predictions = binary_split_predictions  %>%
	left_join(sample_info %>% select(DepMap_ID, cell_line_name), by=c('depmap_id'='DepMap_ID')) %>%
	filter(cell_line_name == "MDA-MB-231") %>%
	left_join(not_triple_neg_summary %>% 
							select(drug, concentration_M, mean_pred) %>%
							rename(mean_non_TN_pred = mean_pred))

mda_summary = mda_predictions %>%
	group_by(drug) %>%
	summarise(mean_pred = mean(.pred_TRUE)) %>%
	arrange(desc(mean_pred))

mda_non_TN_summary = mda_predictions %>%
	group_by(drug, concentration_M) %>%
	summarise(diff = .pred_TRUE - mean_non_TN_pred) %>%
	group_by(drug) %>%
	summarise(mean_diff = mean(diff)) %>%
	arrange(desc(mean_diff))
```

```{r}
deadly_pred_set = mda_predictions %>%
	mutate(drug = fct_relevel(drug,mda_summary$drug)) %>%
	filter(drug %in% mda_summary$drug[1:5])

ggplot(deadly_pred_set, aes(x=log10(concentration_M), y=.pred_TRUE,color=drug)) +
	geom_point() +
	geom_line() + 
	ylim(c(0,1)) +
	labs(x="Log 10 Compound Concentration (M)", 
			 y="Predicted Probability of\nViability Below 90%",
			 color='') +
	BerginskiRMisc::theme_berginski()

ggsave(here('figures/mda_predictions_high_effect.png'),width=5,height=3)
```

```{r}
low_eff_set = mda_predictions %>%
	mutate(drug = fct_relevel(drug,mda_summary$drug)) %>%
	filter(drug %in% rev(mda_summary$drug)[1:5])

ggplot(low_eff_set, aes(x=log10(concentration_M), y=.pred_TRUE,color=drug)) +
	geom_point() +
	geom_line() + 
	ylim(c(0,1)) +
	labs(x="Log 10 Compound Concentration (M)", 
			 y="Predicted Probability of\nViability Below 90%",
			 color='') +
	BerginskiRMisc::theme_berginski()

ggsave(here('figures/mda_predictions_low_effect.png'),width=5,height=3)
```

```{r}
mda_diff_non_TN_set = mda_predictions %>%
	mutate(drug = fct_relevel(drug,mda_non_TN_summary$drug)) %>%
	filter(drug %in% mda_non_TN_summary$drug[1:5]) 

non_TN_diff_set = not_triple_neg_summary %>%
	filter(drug %in% mda_non_TN_summary$drug[1:5]) %>%
	mutate(cell_line_name = "Non-TN") %>%
	rename(.pred_TRUE = mean_pred) %>%
	select(-count)

mda_diff_non_TN_set = mda_diff_non_TN_set %>%
	bind_rows(non_TN_diff_set)

ggplot(mda_diff_non_TN_set, aes(x=log10(concentration_M), y=.pred_TRUE, color=cell_line_name)) +
	geom_point() + 
	geom_line() +
	BerginskiRMisc::theme_berginski() +
	facet_wrap(~drug) 
```



